/*
 * Crescendo API
 * The Crescendo API powers workflow automation and transactional email at scale. Authenticate with a Bearer API key (prefix: `re_...`) obtained from the dashboard.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.crescendo.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.crescendo.model.TemplateVariable;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PublicTemplateResponse
 */
class PublicTemplateResponseTest {
    private final PublicTemplateResponse model = new PublicTemplateResponse();

    /**
     * Model tests for PublicTemplateResponse
     */
    @Test
    void testPublicTemplateResponse() {
        // TODO: test PublicTemplateResponse
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'subject'
     */
    @Test
    void subjectTest() {
        // TODO: test subject
    }

    /**
     * Test the property 'htmlBody'
     */
    @Test
    void htmlBodyTest() {
        // TODO: test htmlBody
    }

    /**
     * Test the property 'textBody'
     */
    @Test
    void textBodyTest() {
        // TODO: test textBody
    }

    /**
     * Test the property 'status'
     */
    @Test
    void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'variables'
     */
    @Test
    void variablesTest() {
        // TODO: test variables
    }

    /**
     * Test the property 'hasPublishedSnapshot'
     */
    @Test
    void hasPublishedSnapshotTest() {
        // TODO: test hasPublishedSnapshot
    }

    /**
     * Test the property 'publishedAt'
     */
    @Test
    void publishedAtTest() {
        // TODO: test publishedAt
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    void updatedAtTest() {
        // TODO: test updatedAt
    }

}
