/*
 * Crescendo API
 * The Crescendo API powers workflow automation and transactional email at scale. Authenticate with a Bearer API key (prefix: `re_...`) obtained from the dashboard.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.crescendo.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SendBatchRequest
 */
class SendBatchRequestTest {
    private final SendBatchRequest model = new SendBatchRequest();

    /**
     * Model tests for SendBatchRequest
     */
    @Test
    void testSendBatchRequest() {
        // TODO: test SendBatchRequest
    }

    /**
     * Test the property 'from'
     */
    @Test
    void fromTest() {
        // TODO: test from
    }

    /**
     * Test the property 'subject'
     */
    @Test
    void subjectTest() {
        // TODO: test subject
    }

    /**
     * Test the property 'htmlBody'
     */
    @Test
    void htmlBodyTest() {
        // TODO: test htmlBody
    }

    /**
     * Test the property 'textBody'
     */
    @Test
    void textBodyTest() {
        // TODO: test textBody
    }

    /**
     * Test the property 'templateId'
     */
    @Test
    void templateIdTest() {
        // TODO: test templateId
    }

    /**
     * Test the property 'templateData'
     */
    @Test
    void templateDataTest() {
        // TODO: test templateData
    }

    /**
     * Test the property 'emailType'
     */
    @Test
    void emailTypeTest() {
        // TODO: test emailType
    }

    /**
     * Test the property 'to'
     */
    @Test
    void toTest() {
        // TODO: test to
    }

}
