/*
 * Crescendo API
 *
 * The Crescendo API powers workflow automation and transactional email at scale. Authenticate with a Bearer API key (prefix: `re_...`) obtained from the dashboard.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Crescendo.Model;
using Crescendo.Client;
using System.Reflection;

namespace Crescendo.Test.Model
{
    /// <summary>
    ///  Class for testing EmailLogResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EmailLogResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EmailLogResponse
        //private EmailLogResponse instance;

        public EmailLogResponseTests()
        {
            // TODO uncomment below to create an instance of EmailLogResponse
            //instance = new EmailLogResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EmailLogResponse
        /// </summary>
        [Fact]
        public void EmailLogResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" EmailLogResponse
            //Assert.IsType<EmailLogResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Fact]
        public void ToTest()
        {
            // TODO unit test for the property 'To'
        }

        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [Fact]
        public void FromTest()
        {
            // TODO unit test for the property 'From'
        }

        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [Fact]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Provider'
        /// </summary>
        [Fact]
        public void ProviderTest()
        {
            // TODO unit test for the property 'Provider'
        }

        /// <summary>
        /// Test the property 'ProviderMessageId'
        /// </summary>
        [Fact]
        public void ProviderMessageIdTest()
        {
            // TODO unit test for the property 'ProviderMessageId'
        }

        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }

        /// <summary>
        /// Test the property 'TemplateId'
        /// </summary>
        [Fact]
        public void TemplateIdTest()
        {
            // TODO unit test for the property 'TemplateId'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'SentAt'
        /// </summary>
        [Fact]
        public void SentAtTest()
        {
            // TODO unit test for the property 'SentAt'
        }

        /// <summary>
        /// Test the property 'OpenedAt'
        /// </summary>
        [Fact]
        public void OpenedAtTest()
        {
            // TODO unit test for the property 'OpenedAt'
        }

        /// <summary>
        /// Test the property 'OpenCount'
        /// </summary>
        [Fact]
        public void OpenCountTest()
        {
            // TODO unit test for the property 'OpenCount'
        }

        /// <summary>
        /// Test the property 'ClickCount'
        /// </summary>
        [Fact]
        public void ClickCountTest()
        {
            // TODO unit test for the property 'ClickCount'
        }
    }
}
