/*
 * Crescendo API
 *
 * The Crescendo API powers workflow automation and transactional email at scale. Authenticate with a Bearer API key (prefix: `re_...`) obtained from the dashboard.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Crescendo.Model;
using Crescendo.Client;
using System.Reflection;

namespace Crescendo.Test.Model
{
    /// <summary>
    ///  Class for testing PublicWebhookResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PublicWebhookResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PublicWebhookResponse
        //private PublicWebhookResponse instance;

        public PublicWebhookResponseTests()
        {
            // TODO uncomment below to create an instance of PublicWebhookResponse
            //instance = new PublicWebhookResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PublicWebhookResponse
        /// </summary>
        [Fact]
        public void PublicWebhookResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" PublicWebhookResponse
            //Assert.IsType<PublicWebhookResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

        /// <summary>
        /// Test the property 'SigningSecret'
        /// </summary>
        [Fact]
        public void SigningSecretTest()
        {
            // TODO unit test for the property 'SigningSecret'
        }

        /// <summary>
        /// Test the property 'SubscribedEvents'
        /// </summary>
        [Fact]
        public void SubscribedEventsTest()
        {
            // TODO unit test for the property 'SubscribedEvents'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
    }
}
