/*
 * Crescendo API
 *
 * The Crescendo API powers workflow automation and transactional email at scale. Authenticate with a Bearer API key (prefix: `re_...`) obtained from the dashboard.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Crescendo.Model;
using Crescendo.Client;
using System.Reflection;

namespace Crescendo.Test.Model
{
    /// <summary>
    ///  Class for testing SuppressionResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SuppressionResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SuppressionResponse
        //private SuppressionResponse instance;

        public SuppressionResponseTests()
        {
            // TODO uncomment below to create an instance of SuppressionResponse
            //instance = new SuppressionResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SuppressionResponse
        /// </summary>
        [Fact]
        public void SuppressionResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" SuppressionResponse
            //Assert.IsType<SuppressionResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'Reason'
        /// </summary>
        [Fact]
        public void ReasonTest()
        {
            // TODO unit test for the property 'Reason'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
    }
}
