/*
 * Crescendo API
 *
 * The Crescendo API powers workflow automation and transactional email at scale. Authenticate with a Bearer API key (prefix: `re_...`) obtained from the dashboard.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Crescendo.Model;
using Crescendo.Client;
using System.Reflection;

namespace Crescendo.Test.Model
{
    /// <summary>
    ///  Class for testing TemplateVariable
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TemplateVariableTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TemplateVariable
        //private TemplateVariable instance;

        public TemplateVariableTests()
        {
            // TODO uncomment below to create an instance of TemplateVariable
            //instance = new TemplateVariable();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TemplateVariable
        /// </summary>
        [Fact]
        public void TemplateVariableInstanceTest()
        {
            // TODO uncomment below to test "IsType" TemplateVariable
            //Assert.IsType<TemplateVariable>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'FallbackValue'
        /// </summary>
        [Fact]
        public void FallbackValueTest()
        {
            // TODO unit test for the property 'FallbackValue'
        }
    }
}
