/*
 * Crescendo API
 *
 * The Crescendo API powers workflow automation and transactional email at scale. Authenticate with a Bearer API key (prefix: `re_...`) obtained from the dashboard.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Crescendo.Model;
using Crescendo.Client;
using System.Reflection;

namespace Crescendo.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateContactRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateContactRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateContactRequest
        //private UpdateContactRequest instance;

        public UpdateContactRequestTests()
        {
            // TODO uncomment below to create an instance of UpdateContactRequest
            //instance = new UpdateContactRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateContactRequest
        /// </summary>
        [Fact]
        public void UpdateContactRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateContactRequest
            //Assert.IsType<UpdateContactRequest>(instance);
        }

        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Fact]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }

        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Fact]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }

        /// <summary>
        /// Test the property 'Subscribed'
        /// </summary>
        [Fact]
        public void SubscribedTest()
        {
            // TODO unit test for the property 'Subscribed'
        }
    }
}
