/*
 * Crescendo API
 *
 * The Crescendo API powers workflow automation and transactional email at scale. Authenticate with a Bearer API key (prefix: `re_...`) obtained from the dashboard.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Crescendo.Model;
using Crescendo.Client;
using System.Reflection;

namespace Crescendo.Test.Model
{
    /// <summary>
    ///  Class for testing WorkflowSummaryResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WorkflowSummaryResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WorkflowSummaryResponse
        //private WorkflowSummaryResponse instance;

        public WorkflowSummaryResponseTests()
        {
            // TODO uncomment below to create an instance of WorkflowSummaryResponse
            //instance = new WorkflowSummaryResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WorkflowSummaryResponse
        /// </summary>
        [Fact]
        public void WorkflowSummaryResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" WorkflowSummaryResponse
            //Assert.IsType<WorkflowSummaryResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'IsActive'
        /// </summary>
        [Fact]
        public void IsActiveTest()
        {
            // TODO unit test for the property 'IsActive'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'StepCount'
        /// </summary>
        [Fact]
        public void StepCountTest()
        {
            // TODO unit test for the property 'StepCount'
        }

        /// <summary>
        /// Test the property 'Revision'
        /// </summary>
        [Fact]
        public void RevisionTest()
        {
            // TODO unit test for the property 'Revision'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

        /// <summary>
        /// Test the property 'LastRunAt'
        /// </summary>
        [Fact]
        public void LastRunAtTest()
        {
            // TODO unit test for the property 'LastRunAt'
        }
    }
}
