<?php
/**
 * AddDomainRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Crescendo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Crescendo API
 *
 * The Crescendo API powers workflow automation and transactional email at scale. Authenticate with a Bearer API key (prefix: `re_...`) obtained from the dashboard.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Crescendo\Model;

use \ArrayAccess;
use \Crescendo\ObjectSerializer;

/**
 * AddDomainRequest Class Doc Comment
 *
 * @category Class
 * @package  Crescendo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AddDomainRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'AddDomainRequest';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'domain_name' => 'string',
        'allowed_email_type' => 'string',
        'credential_source' => 'string',
        'email_provider_connection_id' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'domain_name' => null,
        'allowed_email_type' => null,
        'credential_source' => null,
        'email_provider_connection_id' => 'uuid'
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'domain_name' => false,
        'allowed_email_type' => false,
        'credential_source' => false,
        'email_provider_connection_id' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'domain_name' => 'domainName',
        'allowed_email_type' => 'allowedEmailType',
        'credential_source' => 'credentialSource',
        'email_provider_connection_id' => 'emailProviderConnectionId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'domain_name' => 'setDomainName',
        'allowed_email_type' => 'setAllowedEmailType',
        'credential_source' => 'setCredentialSource',
        'email_provider_connection_id' => 'setEmailProviderConnectionId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'domain_name' => 'getDomainName',
        'allowed_email_type' => 'getAllowedEmailType',
        'credential_source' => 'getCredentialSource',
        'email_provider_connection_id' => 'getEmailProviderConnectionId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const ALLOWED_EMAIL_TYPE_TRANSACTIONAL_ONLY = 'TRANSACTIONAL_ONLY';
    public const ALLOWED_EMAIL_TYPE_MARKETING_AND_BULK = 'MARKETING_AND_BULK';
    public const ALLOWED_EMAIL_TYPE_BOTH = 'BOTH';
    public const CREDENTIAL_SOURCE_PERSONAL = 'PERSONAL';
    public const CREDENTIAL_SOURCE_PLATFORM = 'PLATFORM';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getAllowedEmailTypeAllowableValues()
    {
        return [
            self::ALLOWED_EMAIL_TYPE_TRANSACTIONAL_ONLY,
            self::ALLOWED_EMAIL_TYPE_MARKETING_AND_BULK,
            self::ALLOWED_EMAIL_TYPE_BOTH,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getCredentialSourceAllowableValues()
    {
        return [
            self::CREDENTIAL_SOURCE_PERSONAL,
            self::CREDENTIAL_SOURCE_PLATFORM,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('domain_name', $data ?? [], null);
        $this->setIfExists('allowed_email_type', $data ?? [], null);
        $this->setIfExists('credential_source', $data ?? [], null);
        $this->setIfExists('email_provider_connection_id', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['domain_name'] === null) {
            $invalidProperties[] = "'domain_name' can't be null";
        }
        if ((mb_strlen($this->container['domain_name']) < 1)) {
            $invalidProperties[] = "invalid value for 'domain_name', the character length must be bigger than or equal to 1.";
        }

        $allowedValues = $this->getAllowedEmailTypeAllowableValues();
        if (!is_null($this->container['allowed_email_type']) && !in_array($this->container['allowed_email_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'allowed_email_type', must be one of '%s'",
                $this->container['allowed_email_type'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getCredentialSourceAllowableValues();
        if (!is_null($this->container['credential_source']) && !in_array($this->container['credential_source'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'credential_source', must be one of '%s'",
                $this->container['credential_source'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets domain_name
     *
     * @return string
     */
    public function getDomainName()
    {
        return $this->container['domain_name'];
    }

    /**
     * Sets domain_name
     *
     * @param string $domain_name domain_name
     *
     * @return self
     */
    public function setDomainName($domain_name)
    {
        if (is_null($domain_name)) {
            throw new \InvalidArgumentException('non-nullable domain_name cannot be null');
        }

        if ((mb_strlen($domain_name) < 1)) {
            throw new \InvalidArgumentException('invalid length for $domain_name when calling AddDomainRequest., must be bigger than or equal to 1.');
        }

        $this->container['domain_name'] = $domain_name;

        return $this;
    }

    /**
     * Gets allowed_email_type
     *
     * @return string|null
     */
    public function getAllowedEmailType()
    {
        return $this->container['allowed_email_type'];
    }

    /**
     * Sets allowed_email_type
     *
     * @param string|null $allowed_email_type allowed_email_type
     *
     * @return self
     */
    public function setAllowedEmailType($allowed_email_type)
    {
        if (is_null($allowed_email_type)) {
            throw new \InvalidArgumentException('non-nullable allowed_email_type cannot be null');
        }
        $allowedValues = $this->getAllowedEmailTypeAllowableValues();
        if (!in_array($allowed_email_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'allowed_email_type', must be one of '%s'",
                    $allowed_email_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['allowed_email_type'] = $allowed_email_type;

        return $this;
    }

    /**
     * Gets credential_source
     *
     * @return string|null
     */
    public function getCredentialSource()
    {
        return $this->container['credential_source'];
    }

    /**
     * Sets credential_source
     *
     * @param string|null $credential_source credential_source
     *
     * @return self
     */
    public function setCredentialSource($credential_source)
    {
        if (is_null($credential_source)) {
            throw new \InvalidArgumentException('non-nullable credential_source cannot be null');
        }
        $allowedValues = $this->getCredentialSourceAllowableValues();
        if (!in_array($credential_source, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'credential_source', must be one of '%s'",
                    $credential_source,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['credential_source'] = $credential_source;

        return $this;
    }

    /**
     * Gets email_provider_connection_id
     *
     * @return string|null
     */
    public function getEmailProviderConnectionId()
    {
        return $this->container['email_provider_connection_id'];
    }

    /**
     * Sets email_provider_connection_id
     *
     * @param string|null $email_provider_connection_id email_provider_connection_id
     *
     * @return self
     */
    public function setEmailProviderConnectionId($email_provider_connection_id)
    {
        if (is_null($email_provider_connection_id)) {
            throw new \InvalidArgumentException('non-nullable email_provider_connection_id cannot be null');
        }
        $this->container['email_provider_connection_id'] = $email_provider_connection_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


