=begin
#Crescendo API

#The Crescendo API powers workflow automation and transactional email at scale. Authenticate with a Bearer API key (prefix: `re_...`) obtained from the dashboard.

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Crescendo::WorkflowRunsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'WorkflowRunsApi' do
  before do
    # run before each test
    @api_instance = Crescendo::WorkflowRunsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WorkflowRunsApi' do
    it 'should create an instance of WorkflowRunsApi' do
      expect(@api_instance).to be_instance_of(Crescendo::WorkflowRunsApi)
    end
  end

  # unit tests for cancel_run
  # Cancel workflow run
  # Cancels a pending or currently executing run. Requires run:cancel scope.
  # @param workflow_id 
  # @param run_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'cancel_run test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_run_detail
  # Get run details
  # Gets execution details including step results for a specific run. Requires run:read scope.
  # @param workflow_id 
  # @param run_id 
  # @param [Hash] opts the optional parameters
  # @return [WorkflowRunDetailResponse]
  describe 'get_run_detail test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_run_stats
  # Get run statistics
  # Gets aggregated execution statistics for a workflow. Requires run:read scope.
  # @param workflow_id 
  # @param [Hash] opts the optional parameters
  # @return [WorkflowRunStatsResponse]
  describe 'get_run_stats test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_step_run
  # Get step run details
  # Gets specific step execution details. Requires run:read scope.
  # @param run_id 
  # @param step_run_id 
  # @param [Hash] opts the optional parameters
  # @return [StepRunResponse]
  describe 'get_step_run test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_all_runs
  # List all runs
  # Lists execution runs across all workflows. Requires run:read scope.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page 
  # @option opts [Integer] :size 
  # @return [PageWorkflowRunSummaryResponse]
  describe 'list_all_runs test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_runs
  # List workflow runs
  # Lists all execution runs for a specific workflow. Requires run:read scope.
  # @param workflow_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page 
  # @option opts [Integer] :size 
  # @return [PageWorkflowRunSummaryResponse]
  describe 'list_runs test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_step_runs
  # List step runs
  # Lists step execution details for a specific run. Requires run:read scope.
  # @param run_id 
  # @param [Hash] opts the optional parameters
  # @return [Array<StepRunResponse>]
  describe 'list_step_runs test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
