/*
 * Crescendo API
 * The Crescendo API powers workflow automation and transactional email at scale. Authenticate with a Bearer API key (prefix: `re_...`) obtained from the dashboard.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.crescendo.api;

import io.crescendo.ApiClient;
import io.crescendo.ApiException;
import io.crescendo.ApiResponse;
import io.crescendo.Configuration;
import io.crescendo.Pair;

import io.crescendo.model.ContactResponse;
import io.crescendo.model.CreateContactRequest;
import io.crescendo.model.PublicPageContactResponse;
import java.util.UUID;
import io.crescendo.model.UpdateContactRequest;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-07T13:05:45.810490+05:30[Asia/Kolkata]", comments = "Generator version: 7.23.0")
public class AudiencesContactsApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

  public AudiencesContactsApi() {
    this(Configuration.getDefaultApiClient());
  }

  public AudiencesContactsApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    InputStream responseBody = ApiClient.getResponseBody(response);
    String body = null;
    try {
      body = responseBody == null ? null : new String(responseBody.readAllBytes());
    } finally {
      if (responseBody != null) {
        responseBody.close();
      }
    }
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
    if (responseBody == null) {
      throw new ApiException(new IOException("Response body is empty"));
    }
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * Create a contact
   * Adds a new contact to your audience. Requires contact:write scope.
   * @param createContactRequest  (required)
   * @return ContactResponse
   * @throws ApiException if fails to make API call
   */
  public ContactResponse createContact(@jakarta.annotation.Nonnull CreateContactRequest createContactRequest) throws ApiException {
    return createContact(createContactRequest, null);
  }

  /**
   * Create a contact
   * Adds a new contact to your audience. Requires contact:write scope.
   * @param createContactRequest  (required)
   * @param headers Optional headers to include in the request
   * @return ContactResponse
   * @throws ApiException if fails to make API call
   */
  public ContactResponse createContact(@jakarta.annotation.Nonnull CreateContactRequest createContactRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<ContactResponse> localVarResponse = createContactWithHttpInfo(createContactRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * Create a contact
   * Adds a new contact to your audience. Requires contact:write scope.
   * @param createContactRequest  (required)
   * @return ApiResponse&lt;ContactResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ContactResponse> createContactWithHttpInfo(@jakarta.annotation.Nonnull CreateContactRequest createContactRequest) throws ApiException {
    return createContactWithHttpInfo(createContactRequest, null);
  }

  /**
   * Create a contact
   * Adds a new contact to your audience. Requires contact:write scope.
   * @param createContactRequest  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;ContactResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ContactResponse> createContactWithHttpInfo(@jakarta.annotation.Nonnull CreateContactRequest createContactRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = createContactRequestBuilder(createContactRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("createContact", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<ContactResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        ContactResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<ContactResponse>() {});
        

        return new ApiResponse<ContactResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder createContactRequestBuilder(@jakarta.annotation.Nonnull CreateContactRequest createContactRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'createContactRequest' is set
    if (createContactRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'createContactRequest' when calling createContact");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/audiences";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "*/*");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(createContactRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Delete contact
   * Deletes a contact. Requires contact:write scope.
   * @param contactId  (required)
   * @throws ApiException if fails to make API call
   */
  public void deleteContact(@jakarta.annotation.Nonnull UUID contactId) throws ApiException {
    deleteContact(contactId, null);
  }

  /**
   * Delete contact
   * Deletes a contact. Requires contact:write scope.
   * @param contactId  (required)
   * @param headers Optional headers to include in the request
   * @throws ApiException if fails to make API call
   */
  public void deleteContact(@jakarta.annotation.Nonnull UUID contactId, Map<String, String> headers) throws ApiException {
    deleteContactWithHttpInfo(contactId, headers);
  }

  /**
   * Delete contact
   * Deletes a contact. Requires contact:write scope.
   * @param contactId  (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> deleteContactWithHttpInfo(@jakarta.annotation.Nonnull UUID contactId) throws ApiException {
    return deleteContactWithHttpInfo(contactId, null);
  }

  /**
   * Delete contact
   * Deletes a contact. Requires contact:write scope.
   * @param contactId  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> deleteContactWithHttpInfo(@jakarta.annotation.Nonnull UUID contactId, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = deleteContactRequestBuilder(contactId, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("deleteContact", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody != null) {
          localVarResponseBody.readAllBytes();
        }
        return new ApiResponse<>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            null
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder deleteContactRequestBuilder(@jakarta.annotation.Nonnull UUID contactId, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'contactId' is set
    if (contactId == null) {
      throw new ApiException(400, "Missing the required parameter 'contactId' when calling deleteContact");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/audiences/{contactId}"
        .replace("{contactId}", ApiClient.urlEncode(contactId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("DELETE", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get contact details
   * Gets details for a specific contact. Requires contact:read scope.
   * @param contactId  (required)
   * @return ContactResponse
   * @throws ApiException if fails to make API call
   */
  public ContactResponse getContact(@jakarta.annotation.Nonnull UUID contactId) throws ApiException {
    return getContact(contactId, null);
  }

  /**
   * Get contact details
   * Gets details for a specific contact. Requires contact:read scope.
   * @param contactId  (required)
   * @param headers Optional headers to include in the request
   * @return ContactResponse
   * @throws ApiException if fails to make API call
   */
  public ContactResponse getContact(@jakarta.annotation.Nonnull UUID contactId, Map<String, String> headers) throws ApiException {
    ApiResponse<ContactResponse> localVarResponse = getContactWithHttpInfo(contactId, headers);
    return localVarResponse.getData();
  }

  /**
   * Get contact details
   * Gets details for a specific contact. Requires contact:read scope.
   * @param contactId  (required)
   * @return ApiResponse&lt;ContactResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ContactResponse> getContactWithHttpInfo(@jakarta.annotation.Nonnull UUID contactId) throws ApiException {
    return getContactWithHttpInfo(contactId, null);
  }

  /**
   * Get contact details
   * Gets details for a specific contact. Requires contact:read scope.
   * @param contactId  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;ContactResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ContactResponse> getContactWithHttpInfo(@jakarta.annotation.Nonnull UUID contactId, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getContactRequestBuilder(contactId, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getContact", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<ContactResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        ContactResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<ContactResponse>() {});
        

        return new ApiResponse<ContactResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getContactRequestBuilder(@jakarta.annotation.Nonnull UUID contactId, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'contactId' is set
    if (contactId == null) {
      throw new ApiException(400, "Missing the required parameter 'contactId' when calling getContact");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/audiences/{contactId}"
        .replace("{contactId}", ApiClient.urlEncode(contactId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "*/*");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * List contacts
   * Lists all contacts. Requires contact:read scope.
   * @param limit  (optional, default to 100)
   * @param after  (optional)
   * @return PublicPageContactResponse
   * @throws ApiException if fails to make API call
   */
  public PublicPageContactResponse listContacts(@jakarta.annotation.Nullable Integer limit, @jakarta.annotation.Nullable String after) throws ApiException {
    return listContacts(limit, after, null);
  }

  /**
   * List contacts
   * Lists all contacts. Requires contact:read scope.
   * @param limit  (optional, default to 100)
   * @param after  (optional)
   * @param headers Optional headers to include in the request
   * @return PublicPageContactResponse
   * @throws ApiException if fails to make API call
   */
  public PublicPageContactResponse listContacts(@jakarta.annotation.Nullable Integer limit, @jakarta.annotation.Nullable String after, Map<String, String> headers) throws ApiException {
    ApiResponse<PublicPageContactResponse> localVarResponse = listContactsWithHttpInfo(limit, after, headers);
    return localVarResponse.getData();
  }

  /**
   * List contacts
   * Lists all contacts. Requires contact:read scope.
   * @param limit  (optional, default to 100)
   * @param after  (optional)
   * @return ApiResponse&lt;PublicPageContactResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<PublicPageContactResponse> listContactsWithHttpInfo(@jakarta.annotation.Nullable Integer limit, @jakarta.annotation.Nullable String after) throws ApiException {
    return listContactsWithHttpInfo(limit, after, null);
  }

  /**
   * List contacts
   * Lists all contacts. Requires contact:read scope.
   * @param limit  (optional, default to 100)
   * @param after  (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;PublicPageContactResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<PublicPageContactResponse> listContactsWithHttpInfo(@jakarta.annotation.Nullable Integer limit, @jakarta.annotation.Nullable String after, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = listContactsRequestBuilder(limit, after, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("listContacts", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<PublicPageContactResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        PublicPageContactResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<PublicPageContactResponse>() {});
        

        return new ApiResponse<PublicPageContactResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder listContactsRequestBuilder(@jakarta.annotation.Nullable Integer limit, @jakarta.annotation.Nullable String after, Map<String, String> headers) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/audiences";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "limit";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("limit", limit));
    localVarQueryParameterBaseName = "after";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("after", after));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "*/*");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Update contact
   * Updates a contact. Requires contact:write scope.
   * @param contactId  (required)
   * @param updateContactRequest  (required)
   * @return ContactResponse
   * @throws ApiException if fails to make API call
   */
  public ContactResponse updateContact(@jakarta.annotation.Nonnull UUID contactId, @jakarta.annotation.Nonnull UpdateContactRequest updateContactRequest) throws ApiException {
    return updateContact(contactId, updateContactRequest, null);
  }

  /**
   * Update contact
   * Updates a contact. Requires contact:write scope.
   * @param contactId  (required)
   * @param updateContactRequest  (required)
   * @param headers Optional headers to include in the request
   * @return ContactResponse
   * @throws ApiException if fails to make API call
   */
  public ContactResponse updateContact(@jakarta.annotation.Nonnull UUID contactId, @jakarta.annotation.Nonnull UpdateContactRequest updateContactRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<ContactResponse> localVarResponse = updateContactWithHttpInfo(contactId, updateContactRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * Update contact
   * Updates a contact. Requires contact:write scope.
   * @param contactId  (required)
   * @param updateContactRequest  (required)
   * @return ApiResponse&lt;ContactResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ContactResponse> updateContactWithHttpInfo(@jakarta.annotation.Nonnull UUID contactId, @jakarta.annotation.Nonnull UpdateContactRequest updateContactRequest) throws ApiException {
    return updateContactWithHttpInfo(contactId, updateContactRequest, null);
  }

  /**
   * Update contact
   * Updates a contact. Requires contact:write scope.
   * @param contactId  (required)
   * @param updateContactRequest  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;ContactResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ContactResponse> updateContactWithHttpInfo(@jakarta.annotation.Nonnull UUID contactId, @jakarta.annotation.Nonnull UpdateContactRequest updateContactRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = updateContactRequestBuilder(contactId, updateContactRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("updateContact", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<ContactResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        ContactResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<ContactResponse>() {});
        

        return new ApiResponse<ContactResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder updateContactRequestBuilder(@jakarta.annotation.Nonnull UUID contactId, @jakarta.annotation.Nonnull UpdateContactRequest updateContactRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'contactId' is set
    if (contactId == null) {
      throw new ApiException(400, "Missing the required parameter 'contactId' when calling updateContact");
    }
    // verify the required parameter 'updateContactRequest' is set
    if (updateContactRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'updateContactRequest' when calling updateContact");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/audiences/{contactId}"
        .replace("{contactId}", ApiClient.urlEncode(contactId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "*/*");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(updateContactRequest);
      localVarRequestBuilder.method("PATCH", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
