/*
 * Crescendo API
 * The Crescendo API powers workflow automation and transactional email at scale. Authenticate with a Bearer API key (prefix: `re_...`) obtained from the dashboard.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.crescendo.api;

import io.crescendo.ApiClient;
import io.crescendo.ApiException;
import io.crescendo.ApiResponse;
import io.crescendo.Configuration;
import io.crescendo.Pair;

import io.crescendo.model.EmailLogResponse;
import io.crescendo.model.SendBatchRequest;
import io.crescendo.model.SendBatchResponse;
import io.crescendo.model.SendEmailRequest;
import io.crescendo.model.SendEmailResponse;
import io.crescendo.model.SendTemplatedRequest;
import java.util.UUID;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-07T13:05:45.810490+05:30[Asia/Kolkata]", comments = "Generator version: 7.23.0")
public class EmailsApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

  public EmailsApi() {
    this(Configuration.getDefaultApiClient());
  }

  public EmailsApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    InputStream responseBody = ApiClient.getResponseBody(response);
    String body = null;
    try {
      body = responseBody == null ? null : new String(responseBody.readAllBytes());
    } finally {
      if (responseBody != null) {
        responseBody.close();
      }
    }
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
    if (responseBody == null) {
      throw new ApiException(new IOException("Response body is empty"));
    }
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * Get email details
   * 
   * @param emailId  (required)
   * @return EmailLogResponse
   * @throws ApiException if fails to make API call
   */
  public EmailLogResponse getEmail(@jakarta.annotation.Nonnull UUID emailId) throws ApiException {
    return getEmail(emailId, null);
  }

  /**
   * Get email details
   * 
   * @param emailId  (required)
   * @param headers Optional headers to include in the request
   * @return EmailLogResponse
   * @throws ApiException if fails to make API call
   */
  public EmailLogResponse getEmail(@jakarta.annotation.Nonnull UUID emailId, Map<String, String> headers) throws ApiException {
    ApiResponse<EmailLogResponse> localVarResponse = getEmailWithHttpInfo(emailId, headers);
    return localVarResponse.getData();
  }

  /**
   * Get email details
   * 
   * @param emailId  (required)
   * @return ApiResponse&lt;EmailLogResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<EmailLogResponse> getEmailWithHttpInfo(@jakarta.annotation.Nonnull UUID emailId) throws ApiException {
    return getEmailWithHttpInfo(emailId, null);
  }

  /**
   * Get email details
   * 
   * @param emailId  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;EmailLogResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<EmailLogResponse> getEmailWithHttpInfo(@jakarta.annotation.Nonnull UUID emailId, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getEmailRequestBuilder(emailId, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getEmail", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<EmailLogResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        EmailLogResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<EmailLogResponse>() {});
        

        return new ApiResponse<EmailLogResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getEmailRequestBuilder(@jakarta.annotation.Nonnull UUID emailId, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'emailId' is set
    if (emailId == null) {
      throw new ApiException(400, "Missing the required parameter 'emailId' when calling getEmail");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/emails/{emailId}"
        .replace("{emailId}", ApiClient.urlEncode(emailId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "*/*");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * List emails
   * 
   * @return List&lt;EmailLogResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public List<EmailLogResponse> listEmails() throws ApiException {
    return listEmails(null);
  }

  /**
   * List emails
   * 
   * @param headers Optional headers to include in the request
   * @return List&lt;EmailLogResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public List<EmailLogResponse> listEmails(Map<String, String> headers) throws ApiException {
    ApiResponse<List<EmailLogResponse>> localVarResponse = listEmailsWithHttpInfo(headers);
    return localVarResponse.getData();
  }

  /**
   * List emails
   * 
   * @return ApiResponse&lt;List&lt;EmailLogResponse&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<EmailLogResponse>> listEmailsWithHttpInfo() throws ApiException {
    return listEmailsWithHttpInfo(null);
  }

  /**
   * List emails
   * 
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;List&lt;EmailLogResponse&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<EmailLogResponse>> listEmailsWithHttpInfo(Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = listEmailsRequestBuilder(headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("listEmails", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<List<EmailLogResponse>>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        List<EmailLogResponse> responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<List<EmailLogResponse>>() {});
        

        return new ApiResponse<List<EmailLogResponse>>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder listEmailsRequestBuilder(Map<String, String> headers) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/emails";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "*/*");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Search emails
   * 
   * @param q  (required)
   * @return List&lt;EmailLogResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public List<EmailLogResponse> searchEmails(@jakarta.annotation.Nonnull String q) throws ApiException {
    return searchEmails(q, null);
  }

  /**
   * Search emails
   * 
   * @param q  (required)
   * @param headers Optional headers to include in the request
   * @return List&lt;EmailLogResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public List<EmailLogResponse> searchEmails(@jakarta.annotation.Nonnull String q, Map<String, String> headers) throws ApiException {
    ApiResponse<List<EmailLogResponse>> localVarResponse = searchEmailsWithHttpInfo(q, headers);
    return localVarResponse.getData();
  }

  /**
   * Search emails
   * 
   * @param q  (required)
   * @return ApiResponse&lt;List&lt;EmailLogResponse&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<EmailLogResponse>> searchEmailsWithHttpInfo(@jakarta.annotation.Nonnull String q) throws ApiException {
    return searchEmailsWithHttpInfo(q, null);
  }

  /**
   * Search emails
   * 
   * @param q  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;List&lt;EmailLogResponse&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<EmailLogResponse>> searchEmailsWithHttpInfo(@jakarta.annotation.Nonnull String q, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = searchEmailsRequestBuilder(q, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("searchEmails", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<List<EmailLogResponse>>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        List<EmailLogResponse> responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<List<EmailLogResponse>>() {});
        

        return new ApiResponse<List<EmailLogResponse>>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder searchEmailsRequestBuilder(@jakarta.annotation.Nonnull String q, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'q' is set
    if (q == null) {
      throw new ApiException(400, "Missing the required parameter 'q' when calling searchEmails");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/emails/search";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "q";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("q", q));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "*/*");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * 
   * 
   * @param sendBatchRequest  (required)
   * @return SendBatchResponse
   * @throws ApiException if fails to make API call
   */
  public SendBatchResponse sendBatch(@jakarta.annotation.Nonnull SendBatchRequest sendBatchRequest) throws ApiException {
    return sendBatch(sendBatchRequest, null);
  }

  /**
   * 
   * 
   * @param sendBatchRequest  (required)
   * @param headers Optional headers to include in the request
   * @return SendBatchResponse
   * @throws ApiException if fails to make API call
   */
  public SendBatchResponse sendBatch(@jakarta.annotation.Nonnull SendBatchRequest sendBatchRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<SendBatchResponse> localVarResponse = sendBatchWithHttpInfo(sendBatchRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * 
   * 
   * @param sendBatchRequest  (required)
   * @return ApiResponse&lt;SendBatchResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<SendBatchResponse> sendBatchWithHttpInfo(@jakarta.annotation.Nonnull SendBatchRequest sendBatchRequest) throws ApiException {
    return sendBatchWithHttpInfo(sendBatchRequest, null);
  }

  /**
   * 
   * 
   * @param sendBatchRequest  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;SendBatchResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<SendBatchResponse> sendBatchWithHttpInfo(@jakarta.annotation.Nonnull SendBatchRequest sendBatchRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = sendBatchRequestBuilder(sendBatchRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("sendBatch", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<SendBatchResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        SendBatchResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<SendBatchResponse>() {});
        

        return new ApiResponse<SendBatchResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder sendBatchRequestBuilder(@jakarta.annotation.Nonnull SendBatchRequest sendBatchRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'sendBatchRequest' is set
    if (sendBatchRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'sendBatchRequest' when calling sendBatch");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/emails/batch";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "*/*");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(sendBatchRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * 
   * 
   * @param sendEmailRequest  (required)
   * @return SendEmailResponse
   * @throws ApiException if fails to make API call
   */
  public SendEmailResponse sendEmail(@jakarta.annotation.Nonnull SendEmailRequest sendEmailRequest) throws ApiException {
    return sendEmail(sendEmailRequest, null);
  }

  /**
   * 
   * 
   * @param sendEmailRequest  (required)
   * @param headers Optional headers to include in the request
   * @return SendEmailResponse
   * @throws ApiException if fails to make API call
   */
  public SendEmailResponse sendEmail(@jakarta.annotation.Nonnull SendEmailRequest sendEmailRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<SendEmailResponse> localVarResponse = sendEmailWithHttpInfo(sendEmailRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * 
   * 
   * @param sendEmailRequest  (required)
   * @return ApiResponse&lt;SendEmailResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<SendEmailResponse> sendEmailWithHttpInfo(@jakarta.annotation.Nonnull SendEmailRequest sendEmailRequest) throws ApiException {
    return sendEmailWithHttpInfo(sendEmailRequest, null);
  }

  /**
   * 
   * 
   * @param sendEmailRequest  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;SendEmailResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<SendEmailResponse> sendEmailWithHttpInfo(@jakarta.annotation.Nonnull SendEmailRequest sendEmailRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = sendEmailRequestBuilder(sendEmailRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("sendEmail", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<SendEmailResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        SendEmailResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<SendEmailResponse>() {});
        

        return new ApiResponse<SendEmailResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder sendEmailRequestBuilder(@jakarta.annotation.Nonnull SendEmailRequest sendEmailRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'sendEmailRequest' is set
    if (sendEmailRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'sendEmailRequest' when calling sendEmail");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/emails";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "*/*");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(sendEmailRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * 
   * 
   * @param sendTemplatedRequest  (required)
   * @return SendEmailResponse
   * @throws ApiException if fails to make API call
   */
  public SendEmailResponse sendTemplated(@jakarta.annotation.Nonnull SendTemplatedRequest sendTemplatedRequest) throws ApiException {
    return sendTemplated(sendTemplatedRequest, null);
  }

  /**
   * 
   * 
   * @param sendTemplatedRequest  (required)
   * @param headers Optional headers to include in the request
   * @return SendEmailResponse
   * @throws ApiException if fails to make API call
   */
  public SendEmailResponse sendTemplated(@jakarta.annotation.Nonnull SendTemplatedRequest sendTemplatedRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<SendEmailResponse> localVarResponse = sendTemplatedWithHttpInfo(sendTemplatedRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * 
   * 
   * @param sendTemplatedRequest  (required)
   * @return ApiResponse&lt;SendEmailResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<SendEmailResponse> sendTemplatedWithHttpInfo(@jakarta.annotation.Nonnull SendTemplatedRequest sendTemplatedRequest) throws ApiException {
    return sendTemplatedWithHttpInfo(sendTemplatedRequest, null);
  }

  /**
   * 
   * 
   * @param sendTemplatedRequest  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;SendEmailResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<SendEmailResponse> sendTemplatedWithHttpInfo(@jakarta.annotation.Nonnull SendTemplatedRequest sendTemplatedRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = sendTemplatedRequestBuilder(sendTemplatedRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("sendTemplated", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<SendEmailResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        SendEmailResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<SendEmailResponse>() {});
        

        return new ApiResponse<SendEmailResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder sendTemplatedRequestBuilder(@jakarta.annotation.Nonnull SendTemplatedRequest sendTemplatedRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'sendTemplatedRequest' is set
    if (sendTemplatedRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'sendTemplatedRequest' when calling sendTemplated");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/emails/templated";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "*/*");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(sendTemplatedRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
