/*
 * Crescendo API
 * The Crescendo API powers workflow automation and transactional email at scale. Authenticate with a Bearer API key (prefix: `re_...`) obtained from the dashboard.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.crescendo.api;

import io.crescendo.ApiException;
import io.crescendo.model.ContactResponse;
import io.crescendo.model.CreateContactRequest;
import io.crescendo.model.PublicPageContactResponse;
import java.util.UUID;
import io.crescendo.model.UpdateContactRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for AudiencesContactsApi
 */
@Disabled
public class AudiencesContactsApiTest {

    private final AudiencesContactsApi api = new AudiencesContactsApi();

    
    /**
     * Create a contact
     *
     * Adds a new contact to your audience. Requires contact:write scope.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createContactTest() throws ApiException {
        CreateContactRequest createContactRequest = null;
        ContactResponse response = 
        api.createContact(createContactRequest);
        
        // TODO: test validations
    }
    
    /**
     * Delete contact
     *
     * Deletes a contact. Requires contact:write scope.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteContactTest() throws ApiException {
        UUID contactId = null;
        
        api.deleteContact(contactId);
        
        // TODO: test validations
    }
    
    /**
     * Get contact details
     *
     * Gets details for a specific contact. Requires contact:read scope.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getContactTest() throws ApiException {
        UUID contactId = null;
        ContactResponse response = 
        api.getContact(contactId);
        
        // TODO: test validations
    }
    
    /**
     * List contacts
     *
     * Lists all contacts. Requires contact:read scope.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listContactsTest() throws ApiException {
        Integer limit = null;
        String after = null;
        PublicPageContactResponse response = 
        api.listContacts(limit, after);
        
        // TODO: test validations
    }
    
    /**
     * Update contact
     *
     * Updates a contact. Requires contact:write scope.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateContactTest() throws ApiException {
        UUID contactId = null;
        UpdateContactRequest updateContactRequest = null;
        ContactResponse response = 
        api.updateContact(contactId, updateContactRequest);
        
        // TODO: test validations
    }
    
}
