/*
 * Crescendo API
 * The Crescendo API powers workflow automation and transactional email at scale. Authenticate with a Bearer API key (prefix: `re_...`) obtained from the dashboard.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.crescendo.api;

import io.crescendo.ApiException;
import io.crescendo.model.AddSuppressionRequest;
import io.crescendo.model.ImportSuppressionsRequest;
import io.crescendo.model.PublicPageSuppressionResponse;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for SuppressionsApi
 */
@Disabled
public class SuppressionsApiTest {

    private final SuppressionsApi api = new SuppressionsApi();

    
    /**
     * Add a suppression
     *
     * Manually suppresses an email address. Requires suppression:write scope.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addSuppressionTest() throws ApiException {
        AddSuppressionRequest addSuppressionRequest = null;
        
        api.addSuppression(addSuppressionRequest);
        
        // TODO: test validations
    }
    
    /**
     * Bulk import suppressions
     *
     * Imports a bulk list of suppressions. Requires suppression:import scope.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void importSuppressionsTest() throws ApiException {
        ImportSuppressionsRequest importSuppressionsRequest = null;
        
        api.importSuppressions(importSuppressionsRequest);
        
        // TODO: test validations
    }
    
    /**
     * List suppressions
     *
     * Lists all suppressed email addresses. Requires suppression:read scope.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listSuppressionsTest() throws ApiException {
        Integer limit = null;
        String after = null;
        PublicPageSuppressionResponse response = 
        api.listSuppressions(limit, after);
        
        // TODO: test validations
    }
    
    /**
     * Delete a suppression
     *
     * Removes an email address from the suppression list. Requires suppression:write scope.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void removeSuppressionTest() throws ApiException {
        UUID suppressionId = null;
        
        api.removeSuppression(suppressionId);
        
        // TODO: test validations
    }
    
}
