=begin
#Crescendo API

#The Crescendo API powers workflow automation and transactional email at scale. Authenticate with a Bearer API key (prefix: `re_...`) obtained from the dashboard.

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module Crescendo
  class AppSummaryResponse < ApiModelBase
    attr_accessor :app_key

    attr_accessor :name

    attr_accessor :description

    attr_accessor :logo_url

    attr_accessor :auth_type

    attr_accessor :alt_auth_type

    attr_accessor :credential_schema

    attr_accessor :category

    attr_accessor :help_url

    attr_accessor :internal

    attr_accessor :has_platform_key

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'app_key' => :'appKey',
        :'name' => :'name',
        :'description' => :'description',
        :'logo_url' => :'logoUrl',
        :'auth_type' => :'authType',
        :'alt_auth_type' => :'altAuthType',
        :'credential_schema' => :'credentialSchema',
        :'category' => :'category',
        :'help_url' => :'helpUrl',
        :'internal' => :'internal',
        :'has_platform_key' => :'hasPlatformKey'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'app_key' => :'String',
        :'name' => :'String',
        :'description' => :'String',
        :'logo_url' => :'String',
        :'auth_type' => :'String',
        :'alt_auth_type' => :'String',
        :'credential_schema' => :'Array<Hash<String, Object>>',
        :'category' => :'String',
        :'help_url' => :'String',
        :'internal' => :'Boolean',
        :'has_platform_key' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Crescendo::AppSummaryResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Crescendo::AppSummaryResponse`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'app_key')
        self.app_key = attributes[:'app_key']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'logo_url')
        self.logo_url = attributes[:'logo_url']
      end

      if attributes.key?(:'auth_type')
        self.auth_type = attributes[:'auth_type']
      end

      if attributes.key?(:'alt_auth_type')
        self.alt_auth_type = attributes[:'alt_auth_type']
      end

      if attributes.key?(:'credential_schema')
        if (value = attributes[:'credential_schema']).is_a?(Array)
          self.credential_schema = value
        end
      end

      if attributes.key?(:'category')
        self.category = attributes[:'category']
      end

      if attributes.key?(:'help_url')
        self.help_url = attributes[:'help_url']
      end

      if attributes.key?(:'internal')
        self.internal = attributes[:'internal']
      end

      if attributes.key?(:'has_platform_key')
        self.has_platform_key = attributes[:'has_platform_key']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          app_key == o.app_key &&
          name == o.name &&
          description == o.description &&
          logo_url == o.logo_url &&
          auth_type == o.auth_type &&
          alt_auth_type == o.alt_auth_type &&
          credential_schema == o.credential_schema &&
          category == o.category &&
          help_url == o.help_url &&
          internal == o.internal &&
          has_platform_key == o.has_platform_key
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [app_key, name, description, logo_url, auth_type, alt_auth_type, credential_schema, category, help_url, internal, has_platform_key].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
