// <auto-generated>
/*
 * Crescendo API
 *
 * The Crescendo API powers workflow automation and transactional email at scale. Authenticate with a Bearer API key (prefix: `re_...`) obtained from the dashboard.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Crescendo.Client;

namespace Crescendo.Model
{
    /// <summary>
    /// AddDomainRequest
    /// </summary>
    public partial class AddDomainRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AddDomainRequest" /> class.
        /// </summary>
        /// <param name="domainName">domainName</param>
        /// <param name="allowedEmailType">allowedEmailType</param>
        /// <param name="credentialSource">credentialSource</param>
        /// <param name="emailProviderConnectionId">emailProviderConnectionId</param>
        [JsonConstructor]
        public AddDomainRequest(string domainName, Option<AllowedEmailTypeEnum?> allowedEmailType = default, Option<CredentialSourceEnum?> credentialSource = default, Option<Guid?> emailProviderConnectionId = default)
        {
            DomainName = domainName;
            AllowedEmailTypeOption = allowedEmailType;
            CredentialSourceOption = credentialSource;
            EmailProviderConnectionIdOption = emailProviderConnectionId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines AllowedEmailType
        /// </summary>
        public enum AllowedEmailTypeEnum
        {
            /// <summary>
            /// Enum TRANSACTIONALONLY for value: TRANSACTIONAL_ONLY
            /// </summary>
            TRANSACTIONALONLY = 1,

            /// <summary>
            /// Enum MARKETINGANDBULK for value: MARKETING_AND_BULK
            /// </summary>
            MARKETINGANDBULK = 2,

            /// <summary>
            /// Enum BOTH for value: BOTH
            /// </summary>
            BOTH = 3
        }

        /// <summary>
        /// Returns a <see cref="AllowedEmailTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static AllowedEmailTypeEnum AllowedEmailTypeEnumFromString(string value)
        {
            if (value.Equals("TRANSACTIONAL_ONLY"))
                return AllowedEmailTypeEnum.TRANSACTIONALONLY;

            if (value.Equals("MARKETING_AND_BULK"))
                return AllowedEmailTypeEnum.MARKETINGANDBULK;

            if (value.Equals("BOTH"))
                return AllowedEmailTypeEnum.BOTH;

            throw new NotImplementedException($"Could not convert value to type AllowedEmailTypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="AllowedEmailTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static AllowedEmailTypeEnum? AllowedEmailTypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("TRANSACTIONAL_ONLY"))
                return AllowedEmailTypeEnum.TRANSACTIONALONLY;

            if (value.Equals("MARKETING_AND_BULK"))
                return AllowedEmailTypeEnum.MARKETINGANDBULK;

            if (value.Equals("BOTH"))
                return AllowedEmailTypeEnum.BOTH;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="AllowedEmailTypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string AllowedEmailTypeEnumToJsonValue(AllowedEmailTypeEnum? value)
        {
            if (value == AllowedEmailTypeEnum.TRANSACTIONALONLY)
                return "TRANSACTIONAL_ONLY";

            if (value == AllowedEmailTypeEnum.MARKETINGANDBULK)
                return "MARKETING_AND_BULK";

            if (value == AllowedEmailTypeEnum.BOTH)
                return "BOTH";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of AllowedEmailType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<AllowedEmailTypeEnum?> AllowedEmailTypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets AllowedEmailType
        /// </summary>
        [JsonPropertyName("allowedEmailType")]
        public AllowedEmailTypeEnum? AllowedEmailType { get { return this.AllowedEmailTypeOption.Value; } set { this.AllowedEmailTypeOption = new(value); } }

        /// <summary>
        /// Defines CredentialSource
        /// </summary>
        public enum CredentialSourceEnum
        {
            /// <summary>
            /// Enum PERSONAL for value: PERSONAL
            /// </summary>
            PERSONAL = 1,

            /// <summary>
            /// Enum PLATFORM for value: PLATFORM
            /// </summary>
            PLATFORM = 2
        }

        /// <summary>
        /// Returns a <see cref="CredentialSourceEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static CredentialSourceEnum CredentialSourceEnumFromString(string value)
        {
            if (value.Equals("PERSONAL"))
                return CredentialSourceEnum.PERSONAL;

            if (value.Equals("PLATFORM"))
                return CredentialSourceEnum.PLATFORM;

            throw new NotImplementedException($"Could not convert value to type CredentialSourceEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="CredentialSourceEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static CredentialSourceEnum? CredentialSourceEnumFromStringOrDefault(string value)
        {
            if (value.Equals("PERSONAL"))
                return CredentialSourceEnum.PERSONAL;

            if (value.Equals("PLATFORM"))
                return CredentialSourceEnum.PLATFORM;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="CredentialSourceEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string CredentialSourceEnumToJsonValue(CredentialSourceEnum? value)
        {
            if (value == CredentialSourceEnum.PERSONAL)
                return "PERSONAL";

            if (value == CredentialSourceEnum.PLATFORM)
                return "PLATFORM";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of CredentialSource
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<CredentialSourceEnum?> CredentialSourceOption { get; private set; }

        /// <summary>
        /// Gets or Sets CredentialSource
        /// </summary>
        [JsonPropertyName("credentialSource")]
        public CredentialSourceEnum? CredentialSource { get { return this.CredentialSourceOption.Value; } set { this.CredentialSourceOption = new(value); } }

        /// <summary>
        /// Gets or Sets DomainName
        /// </summary>
        [JsonPropertyName("domainName")]
        public string DomainName { get; set; }

        /// <summary>
        /// Used to track the state of EmailProviderConnectionId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> EmailProviderConnectionIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets EmailProviderConnectionId
        /// </summary>
        [JsonPropertyName("emailProviderConnectionId")]
        public Guid? EmailProviderConnectionId { get { return this.EmailProviderConnectionIdOption.Value; } set { this.EmailProviderConnectionIdOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AddDomainRequest {\n");
            sb.Append("  DomainName: ").Append(DomainName).Append("\n");
            sb.Append("  AllowedEmailType: ").Append(AllowedEmailType).Append("\n");
            sb.Append("  CredentialSource: ").Append(CredentialSource).Append("\n");
            sb.Append("  EmailProviderConnectionId: ").Append(EmailProviderConnectionId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // DomainName (string) minLength
            if (this.DomainName != null && this.DomainName.Length < 1)
            {
                yield return new ValidationResult("Invalid value for DomainName, length must be greater than 1.", new [] { "DomainName" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="AddDomainRequest" />
    /// </summary>
    public class AddDomainRequestJsonConverter : JsonConverter<AddDomainRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="AddDomainRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override AddDomainRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> domainName = default;
            Option<AddDomainRequest.AllowedEmailTypeEnum?> allowedEmailType = default;
            Option<AddDomainRequest.CredentialSourceEnum?> credentialSource = default;
            Option<Guid?> emailProviderConnectionId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "domainName":
                            domainName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "allowedEmailType":
                            string? allowedEmailTypeRawValue = utf8JsonReader.GetString();
                            if (allowedEmailTypeRawValue != null)
                                allowedEmailType = new Option<AddDomainRequest.AllowedEmailTypeEnum?>(AddDomainRequest.AllowedEmailTypeEnumFromStringOrDefault(allowedEmailTypeRawValue));
                            break;
                        case "credentialSource":
                            string? credentialSourceRawValue = utf8JsonReader.GetString();
                            if (credentialSourceRawValue != null)
                                credentialSource = new Option<AddDomainRequest.CredentialSourceEnum?>(AddDomainRequest.CredentialSourceEnumFromStringOrDefault(credentialSourceRawValue));
                            break;
                        case "emailProviderConnectionId":
                            emailProviderConnectionId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!domainName.IsSet)
                throw new ArgumentException("Property is required for class AddDomainRequest.", nameof(domainName));

            if (domainName.IsSet && domainName.Value == null)
                throw new ArgumentNullException(nameof(domainName), "Property is not nullable for class AddDomainRequest.");

            if (allowedEmailType.IsSet && allowedEmailType.Value == null)
                throw new ArgumentNullException(nameof(allowedEmailType), "Property is not nullable for class AddDomainRequest.");

            if (credentialSource.IsSet && credentialSource.Value == null)
                throw new ArgumentNullException(nameof(credentialSource), "Property is not nullable for class AddDomainRequest.");

            if (emailProviderConnectionId.IsSet && emailProviderConnectionId.Value == null)
                throw new ArgumentNullException(nameof(emailProviderConnectionId), "Property is not nullable for class AddDomainRequest.");

            return new AddDomainRequest(domainName.Value!, allowedEmailType, credentialSource, emailProviderConnectionId);
        }

        /// <summary>
        /// Serializes a <see cref="AddDomainRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="addDomainRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, AddDomainRequest addDomainRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, addDomainRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="AddDomainRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="addDomainRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, AddDomainRequest addDomainRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (addDomainRequest.DomainName == null)
                throw new ArgumentNullException(nameof(addDomainRequest.DomainName), "Property is required for class AddDomainRequest.");

            writer.WriteString("domainName", addDomainRequest.DomainName);

            var allowedEmailTypeRawValue = AddDomainRequest.AllowedEmailTypeEnumToJsonValue(addDomainRequest.AllowedEmailTypeOption.Value!.Value);
            writer.WriteString("allowedEmailType", allowedEmailTypeRawValue);
            var credentialSourceRawValue = AddDomainRequest.CredentialSourceEnumToJsonValue(addDomainRequest.CredentialSourceOption.Value!.Value);
            writer.WriteString("credentialSource", credentialSourceRawValue);
            if (addDomainRequest.EmailProviderConnectionIdOption.IsSet)
                writer.WriteString("emailProviderConnectionId", addDomainRequest.EmailProviderConnectionIdOption.Value!.Value);
        }
    }
}
