// <auto-generated>
/*
 * Crescendo API
 *
 * The Crescendo API powers workflow automation and transactional email at scale. Authenticate with a Bearer API key (prefix: `re_...`) obtained from the dashboard.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Crescendo.Client;

namespace Crescendo.Model
{
    /// <summary>
    /// CreateCustomEventRequest
    /// </summary>
    public partial class CreateCustomEventRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateCustomEventRequest" /> class.
        /// </summary>
        /// <param name="name">name</param>
        /// <param name="jsonSchema">jsonSchema</param>
        [JsonConstructor]
        public CreateCustomEventRequest(Option<string?> name = default, Option<Dictionary<string, Object>?> jsonSchema = default)
        {
            NameOption = name;
            JsonSchemaOption = jsonSchema;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption.Value; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of JsonSchema
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Dictionary<string, Object>?> JsonSchemaOption { get; private set; }

        /// <summary>
        /// Gets or Sets JsonSchema
        /// </summary>
        [JsonPropertyName("jsonSchema")]
        public Dictionary<string, Object>? JsonSchema { get { return this.JsonSchemaOption.Value; } set { this.JsonSchemaOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateCustomEventRequest {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  JsonSchema: ").Append(JsonSchema).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CreateCustomEventRequest" />
    /// </summary>
    public class CreateCustomEventRequestJsonConverter : JsonConverter<CreateCustomEventRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="CreateCustomEventRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CreateCustomEventRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> name = default;
            Option<Dictionary<string, Object>?> jsonSchema = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "jsonSchema":
                            jsonSchema = new Option<Dictionary<string, Object>?>(JsonSerializer.Deserialize<Dictionary<string, Object>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class CreateCustomEventRequest.");

            if (jsonSchema.IsSet && jsonSchema.Value == null)
                throw new ArgumentNullException(nameof(jsonSchema), "Property is not nullable for class CreateCustomEventRequest.");

            return new CreateCustomEventRequest(name, jsonSchema);
        }

        /// <summary>
        /// Serializes a <see cref="CreateCustomEventRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createCustomEventRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CreateCustomEventRequest createCustomEventRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, createCustomEventRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CreateCustomEventRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createCustomEventRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CreateCustomEventRequest createCustomEventRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (createCustomEventRequest.NameOption.IsSet && createCustomEventRequest.Name == null)
                throw new ArgumentNullException(nameof(createCustomEventRequest.Name), "Property is required for class CreateCustomEventRequest.");

            if (createCustomEventRequest.JsonSchemaOption.IsSet && createCustomEventRequest.JsonSchema == null)
                throw new ArgumentNullException(nameof(createCustomEventRequest.JsonSchema), "Property is required for class CreateCustomEventRequest.");

            if (createCustomEventRequest.NameOption.IsSet)
                writer.WriteString("name", createCustomEventRequest.Name);

            if (createCustomEventRequest.JsonSchemaOption.IsSet)
            {
                writer.WritePropertyName("jsonSchema");
                JsonSerializer.Serialize(writer, createCustomEventRequest.JsonSchema, jsonSerializerOptions);
            }
        }
    }
}
