// <auto-generated>
/*
 * Crescendo API
 *
 * The Crescendo API powers workflow automation and transactional email at scale. Authenticate with a Bearer API key (prefix: `re_...`) obtained from the dashboard.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Crescendo.Client;

namespace Crescendo.Model
{
    /// <summary>
    /// ImportSuppressionsRequest
    /// </summary>
    public partial class ImportSuppressionsRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ImportSuppressionsRequest" /> class.
        /// </summary>
        /// <param name="emails">emails</param>
        [JsonConstructor]
        public ImportSuppressionsRequest(Option<List<string>?> emails = default)
        {
            EmailsOption = emails;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Emails
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> EmailsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Emails
        /// </summary>
        [JsonPropertyName("emails")]
        public List<string>? Emails { get { return this.EmailsOption.Value; } set { this.EmailsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ImportSuppressionsRequest {\n");
            sb.Append("  Emails: ").Append(Emails).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ImportSuppressionsRequest" />
    /// </summary>
    public class ImportSuppressionsRequestJsonConverter : JsonConverter<ImportSuppressionsRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="ImportSuppressionsRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ImportSuppressionsRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<string>?> emails = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "emails":
                            emails = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (emails.IsSet && emails.Value == null)
                throw new ArgumentNullException(nameof(emails), "Property is not nullable for class ImportSuppressionsRequest.");

            return new ImportSuppressionsRequest(emails);
        }

        /// <summary>
        /// Serializes a <see cref="ImportSuppressionsRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="importSuppressionsRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ImportSuppressionsRequest importSuppressionsRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, importSuppressionsRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ImportSuppressionsRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="importSuppressionsRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ImportSuppressionsRequest importSuppressionsRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (importSuppressionsRequest.EmailsOption.IsSet && importSuppressionsRequest.Emails == null)
                throw new ArgumentNullException(nameof(importSuppressionsRequest.Emails), "Property is required for class ImportSuppressionsRequest.");

            if (importSuppressionsRequest.EmailsOption.IsSet)
            {
                writer.WritePropertyName("emails");
                JsonSerializer.Serialize(writer, importSuppressionsRequest.Emails, jsonSerializerOptions);
            }
        }
    }
}
