// <auto-generated>
/*
 * Crescendo API
 *
 * The Crescendo API powers workflow automation and transactional email at scale. Authenticate with a Bearer API key (prefix: `re_...`) obtained from the dashboard.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Crescendo.Client;

namespace Crescendo.Model
{
    /// <summary>
    /// SendEmailRequest
    /// </summary>
    public partial class SendEmailRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SendEmailRequest" /> class.
        /// </summary>
        /// <param name="from">from</param>
        /// <param name="to">to</param>
        /// <param name="subject">subject</param>
        /// <param name="emailType">emailType</param>
        /// <param name="htmlBody">htmlBody</param>
        /// <param name="textBody">textBody</param>
        /// <param name="templateId">templateId</param>
        /// <param name="templateData">templateData</param>
        [JsonConstructor]
        public SendEmailRequest(string from, string to, string subject, EmailTypeEnum emailType, Option<string?> htmlBody = default, Option<string?> textBody = default, Option<Guid?> templateId = default, Option<Dictionary<string, Object>?> templateData = default)
        {
            From = from;
            To = to;
            Subject = subject;
            EmailType = emailType;
            HtmlBodyOption = htmlBody;
            TextBodyOption = textBody;
            TemplateIdOption = templateId;
            TemplateDataOption = templateData;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines EmailType
        /// </summary>
        public enum EmailTypeEnum
        {
            /// <summary>
            /// Enum TRANSACTIONAL for value: TRANSACTIONAL
            /// </summary>
            TRANSACTIONAL = 1,

            /// <summary>
            /// Enum MARKETING for value: MARKETING
            /// </summary>
            MARKETING = 2
        }

        /// <summary>
        /// Returns a <see cref="EmailTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static EmailTypeEnum EmailTypeEnumFromString(string value)
        {
            if (value.Equals("TRANSACTIONAL"))
                return EmailTypeEnum.TRANSACTIONAL;

            if (value.Equals("MARKETING"))
                return EmailTypeEnum.MARKETING;

            throw new NotImplementedException($"Could not convert value to type EmailTypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="EmailTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static EmailTypeEnum? EmailTypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("TRANSACTIONAL"))
                return EmailTypeEnum.TRANSACTIONAL;

            if (value.Equals("MARKETING"))
                return EmailTypeEnum.MARKETING;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="EmailTypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string EmailTypeEnumToJsonValue(EmailTypeEnum value)
        {
            if (value == EmailTypeEnum.TRANSACTIONAL)
                return "TRANSACTIONAL";

            if (value == EmailTypeEnum.MARKETING)
                return "MARKETING";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets EmailType
        /// </summary>
        [JsonPropertyName("emailType")]
        public EmailTypeEnum EmailType { get; set; }

        /// <summary>
        /// Gets or Sets From
        /// </summary>
        [JsonPropertyName("from")]
        public string From { get; set; }

        /// <summary>
        /// Gets or Sets To
        /// </summary>
        [JsonPropertyName("to")]
        public string To { get; set; }

        /// <summary>
        /// Gets or Sets Subject
        /// </summary>
        [JsonPropertyName("subject")]
        public string Subject { get; set; }

        /// <summary>
        /// Used to track the state of HtmlBody
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> HtmlBodyOption { get; private set; }

        /// <summary>
        /// Gets or Sets HtmlBody
        /// </summary>
        [JsonPropertyName("htmlBody")]
        public string? HtmlBody { get { return this.HtmlBodyOption.Value; } set { this.HtmlBodyOption = new(value); } }

        /// <summary>
        /// Used to track the state of TextBody
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TextBodyOption { get; private set; }

        /// <summary>
        /// Gets or Sets TextBody
        /// </summary>
        [JsonPropertyName("textBody")]
        public string? TextBody { get { return this.TextBodyOption.Value; } set { this.TextBodyOption = new(value); } }

        /// <summary>
        /// Used to track the state of TemplateId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> TemplateIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets TemplateId
        /// </summary>
        [JsonPropertyName("templateId")]
        public Guid? TemplateId { get { return this.TemplateIdOption.Value; } set { this.TemplateIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of TemplateData
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Dictionary<string, Object>?> TemplateDataOption { get; private set; }

        /// <summary>
        /// Gets or Sets TemplateData
        /// </summary>
        [JsonPropertyName("templateData")]
        public Dictionary<string, Object>? TemplateData { get { return this.TemplateDataOption.Value; } set { this.TemplateDataOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SendEmailRequest {\n");
            sb.Append("  From: ").Append(From).Append("\n");
            sb.Append("  To: ").Append(To).Append("\n");
            sb.Append("  Subject: ").Append(Subject).Append("\n");
            sb.Append("  EmailType: ").Append(EmailType).Append("\n");
            sb.Append("  HtmlBody: ").Append(HtmlBody).Append("\n");
            sb.Append("  TextBody: ").Append(TextBody).Append("\n");
            sb.Append("  TemplateId: ").Append(TemplateId).Append("\n");
            sb.Append("  TemplateData: ").Append(TemplateData).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // From (string) minLength
            if (this.From != null && this.From.Length < 1)
            {
                yield return new ValidationResult("Invalid value for From, length must be greater than 1.", new [] { "From" });
            }

            // To (string) minLength
            if (this.To != null && this.To.Length < 1)
            {
                yield return new ValidationResult("Invalid value for To, length must be greater than 1.", new [] { "To" });
            }

            // Subject (string) minLength
            if (this.Subject != null && this.Subject.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Subject, length must be greater than 1.", new [] { "Subject" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SendEmailRequest" />
    /// </summary>
    public class SendEmailRequestJsonConverter : JsonConverter<SendEmailRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="SendEmailRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SendEmailRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> from = default;
            Option<string?> to = default;
            Option<string?> subject = default;
            Option<SendEmailRequest.EmailTypeEnum?> emailType = default;
            Option<string?> htmlBody = default;
            Option<string?> textBody = default;
            Option<Guid?> templateId = default;
            Option<Dictionary<string, Object>?> templateData = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "from":
                            from = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "to":
                            to = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "subject":
                            subject = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "emailType":
                            string? emailTypeRawValue = utf8JsonReader.GetString();
                            if (emailTypeRawValue != null)
                                emailType = new Option<SendEmailRequest.EmailTypeEnum?>(SendEmailRequest.EmailTypeEnumFromStringOrDefault(emailTypeRawValue));
                            break;
                        case "htmlBody":
                            htmlBody = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "textBody":
                            textBody = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "templateId":
                            templateId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "templateData":
                            templateData = new Option<Dictionary<string, Object>?>(JsonSerializer.Deserialize<Dictionary<string, Object>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!from.IsSet)
                throw new ArgumentException("Property is required for class SendEmailRequest.", nameof(from));

            if (!to.IsSet)
                throw new ArgumentException("Property is required for class SendEmailRequest.", nameof(to));

            if (!subject.IsSet)
                throw new ArgumentException("Property is required for class SendEmailRequest.", nameof(subject));

            if (!emailType.IsSet)
                throw new ArgumentException("Property is required for class SendEmailRequest.", nameof(emailType));

            if (from.IsSet && from.Value == null)
                throw new ArgumentNullException(nameof(from), "Property is not nullable for class SendEmailRequest.");

            if (to.IsSet && to.Value == null)
                throw new ArgumentNullException(nameof(to), "Property is not nullable for class SendEmailRequest.");

            if (subject.IsSet && subject.Value == null)
                throw new ArgumentNullException(nameof(subject), "Property is not nullable for class SendEmailRequest.");

            if (emailType.IsSet && emailType.Value == null)
                throw new ArgumentNullException(nameof(emailType), "Property is not nullable for class SendEmailRequest.");

            if (htmlBody.IsSet && htmlBody.Value == null)
                throw new ArgumentNullException(nameof(htmlBody), "Property is not nullable for class SendEmailRequest.");

            if (textBody.IsSet && textBody.Value == null)
                throw new ArgumentNullException(nameof(textBody), "Property is not nullable for class SendEmailRequest.");

            if (templateId.IsSet && templateId.Value == null)
                throw new ArgumentNullException(nameof(templateId), "Property is not nullable for class SendEmailRequest.");

            if (templateData.IsSet && templateData.Value == null)
                throw new ArgumentNullException(nameof(templateData), "Property is not nullable for class SendEmailRequest.");

            return new SendEmailRequest(from.Value!, to.Value!, subject.Value!, emailType.Value!.Value!, htmlBody, textBody, templateId, templateData);
        }

        /// <summary>
        /// Serializes a <see cref="SendEmailRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="sendEmailRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SendEmailRequest sendEmailRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, sendEmailRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SendEmailRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="sendEmailRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SendEmailRequest sendEmailRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (sendEmailRequest.From == null)
                throw new ArgumentNullException(nameof(sendEmailRequest.From), "Property is required for class SendEmailRequest.");

            if (sendEmailRequest.To == null)
                throw new ArgumentNullException(nameof(sendEmailRequest.To), "Property is required for class SendEmailRequest.");

            if (sendEmailRequest.Subject == null)
                throw new ArgumentNullException(nameof(sendEmailRequest.Subject), "Property is required for class SendEmailRequest.");

            if (sendEmailRequest.HtmlBodyOption.IsSet && sendEmailRequest.HtmlBody == null)
                throw new ArgumentNullException(nameof(sendEmailRequest.HtmlBody), "Property is required for class SendEmailRequest.");

            if (sendEmailRequest.TextBodyOption.IsSet && sendEmailRequest.TextBody == null)
                throw new ArgumentNullException(nameof(sendEmailRequest.TextBody), "Property is required for class SendEmailRequest.");

            if (sendEmailRequest.TemplateDataOption.IsSet && sendEmailRequest.TemplateData == null)
                throw new ArgumentNullException(nameof(sendEmailRequest.TemplateData), "Property is required for class SendEmailRequest.");

            writer.WriteString("from", sendEmailRequest.From);

            writer.WriteString("to", sendEmailRequest.To);

            writer.WriteString("subject", sendEmailRequest.Subject);

            var emailTypeRawValue = SendEmailRequest.EmailTypeEnumToJsonValue(sendEmailRequest.EmailType);
            writer.WriteString("emailType", emailTypeRawValue);
            if (sendEmailRequest.HtmlBodyOption.IsSet)
                writer.WriteString("htmlBody", sendEmailRequest.HtmlBody);

            if (sendEmailRequest.TextBodyOption.IsSet)
                writer.WriteString("textBody", sendEmailRequest.TextBody);

            if (sendEmailRequest.TemplateIdOption.IsSet)
                writer.WriteString("templateId", sendEmailRequest.TemplateIdOption.Value!.Value);

            if (sendEmailRequest.TemplateDataOption.IsSet)
            {
                writer.WritePropertyName("templateData");
                JsonSerializer.Serialize(writer, sendEmailRequest.TemplateData, jsonSerializerOptions);
            }
        }
    }
}
