/*
 * Crescendo API
 *
 * The Crescendo API powers workflow automation and transactional email at scale. Authenticate with a Bearer API key (prefix: `re_...`) obtained from the dashboard.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EmailLogResponse {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "to", skip_serializing_if = "Option::is_none")]
    pub to: Option<String>,
    #[serde(rename = "from", skip_serializing_if = "Option::is_none")]
    pub from: Option<String>,
    #[serde(rename = "subject", skip_serializing_if = "Option::is_none")]
    pub subject: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "provider", skip_serializing_if = "Option::is_none")]
    pub provider: Option<String>,
    #[serde(rename = "providerMessageId", skip_serializing_if = "Option::is_none")]
    pub provider_message_id: Option<String>,
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    #[serde(rename = "templateId", skip_serializing_if = "Option::is_none")]
    pub template_id: Option<uuid::Uuid>,
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "sentAt", skip_serializing_if = "Option::is_none")]
    pub sent_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "openedAt", skip_serializing_if = "Option::is_none")]
    pub opened_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "openCount", skip_serializing_if = "Option::is_none")]
    pub open_count: Option<i32>,
    #[serde(rename = "clickCount", skip_serializing_if = "Option::is_none")]
    pub click_count: Option<i32>,
}

impl EmailLogResponse {
    pub fn new() -> EmailLogResponse {
        EmailLogResponse {
            id: None,
            to: None,
            from: None,
            subject: None,
            status: None,
            provider: None,
            provider_message_id: None,
            error: None,
            template_id: None,
            created_at: None,
            sent_at: None,
            opened_at: None,
            open_count: None,
            click_count: None,
        }
    }
}

