/*
 * Crescendo API
 *
 * The Crescendo API powers workflow automation and transactional email at scale. Authenticate with a Bearer API key (prefix: `re_...`) obtained from the dashboard.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicTestSendResponse {
    #[serde(rename = "emailLogId", skip_serializing_if = "Option::is_none")]
    pub email_log_id: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
}

impl PublicTestSendResponse {
    pub fn new() -> PublicTestSendResponse {
        PublicTestSendResponse {
            email_log_id: None,
            status: None,
        }
    }
}

