=begin
#Crescendo API

#The Crescendo API powers workflow automation and transactional email at scale. Authenticate with a Bearer API key (prefix: `re_...`) obtained from the dashboard.

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Crescendo::PublicPageDomainResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Crescendo::PublicPageDomainResponse do
  #let(:instance) { Crescendo::PublicPageDomainResponse.new }

  describe 'test an instance of PublicPageDomainResponse' do
    it 'should create an instance of PublicPageDomainResponse' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Crescendo::PublicPageDomainResponse)
    end
  end

  describe 'test attribute "data"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "has_more"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "next_cursor"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
