=begin
#Crescendo API

#The Crescendo API powers workflow automation and transactional email at scale. Authenticate with a Bearer API key (prefix: `re_...`) obtained from the dashboard.

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Crescendo::SendTemplatedRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Crescendo::SendTemplatedRequest do
  #let(:instance) { Crescendo::SendTemplatedRequest.new }

  describe 'test an instance of SendTemplatedRequest' do
    it 'should create an instance of SendTemplatedRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Crescendo::SendTemplatedRequest)
    end
  end

  describe 'test attribute "from"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "to"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "template_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "template_data"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "email_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["TRANSACTIONAL", "MARKETING"])
      # validator.allowable_values.each do |value|
      #   expect { instance.email_type = value }.not_to raise_error
      # end
    end
  end

end
