// <auto-generated>
/*
 * Crescendo API
 *
 * The Crescendo API powers workflow automation and transactional email at scale. Authenticate with a Bearer API key (prefix: `re_...`) obtained from the dashboard.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System.Linq;
using System.Collections.Generic;

namespace Crescendo.Client
{
    /// <summary>
    /// A class containing a CookieContainer
    /// </summary>
    public sealed class CookieContainer
    {
        /// <summary>
        /// The collection of tokens
        /// </summary>
        public System.Net.CookieContainer Value { get; } = new System.Net.CookieContainer();
    }
}
