/*
Crescendo API

The Crescendo API powers workflow automation and transactional email at scale. Authenticate with a Bearer API key (prefix: `re_...`) obtained from the dashboard.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crescendo

import (
	"encoding/json"
)

// checks if the UpdateTemplateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateTemplateRequest{}

// UpdateTemplateRequest struct for UpdateTemplateRequest
type UpdateTemplateRequest struct {
	Name *string `json:"name,omitempty"`
	Subject *string `json:"subject,omitempty"`
	HtmlBody *string `json:"htmlBody,omitempty"`
	TextBody *string `json:"textBody,omitempty"`
	Variables []TemplateVariable `json:"variables,omitempty"`
}

// NewUpdateTemplateRequest instantiates a new UpdateTemplateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateTemplateRequest() *UpdateTemplateRequest {
	this := UpdateTemplateRequest{}
	return &this
}

// NewUpdateTemplateRequestWithDefaults instantiates a new UpdateTemplateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateTemplateRequestWithDefaults() *UpdateTemplateRequest {
	this := UpdateTemplateRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateTemplateRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTemplateRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateTemplateRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateTemplateRequest) SetName(v string) {
	o.Name = &v
}

// GetSubject returns the Subject field value if set, zero value otherwise.
func (o *UpdateTemplateRequest) GetSubject() string {
	if o == nil || IsNil(o.Subject) {
		var ret string
		return ret
	}
	return *o.Subject
}

// GetSubjectOk returns a tuple with the Subject field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTemplateRequest) GetSubjectOk() (*string, bool) {
	if o == nil || IsNil(o.Subject) {
		return nil, false
	}
	return o.Subject, true
}

// HasSubject returns a boolean if a field has been set.
func (o *UpdateTemplateRequest) HasSubject() bool {
	if o != nil && !IsNil(o.Subject) {
		return true
	}

	return false
}

// SetSubject gets a reference to the given string and assigns it to the Subject field.
func (o *UpdateTemplateRequest) SetSubject(v string) {
	o.Subject = &v
}

// GetHtmlBody returns the HtmlBody field value if set, zero value otherwise.
func (o *UpdateTemplateRequest) GetHtmlBody() string {
	if o == nil || IsNil(o.HtmlBody) {
		var ret string
		return ret
	}
	return *o.HtmlBody
}

// GetHtmlBodyOk returns a tuple with the HtmlBody field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTemplateRequest) GetHtmlBodyOk() (*string, bool) {
	if o == nil || IsNil(o.HtmlBody) {
		return nil, false
	}
	return o.HtmlBody, true
}

// HasHtmlBody returns a boolean if a field has been set.
func (o *UpdateTemplateRequest) HasHtmlBody() bool {
	if o != nil && !IsNil(o.HtmlBody) {
		return true
	}

	return false
}

// SetHtmlBody gets a reference to the given string and assigns it to the HtmlBody field.
func (o *UpdateTemplateRequest) SetHtmlBody(v string) {
	o.HtmlBody = &v
}

// GetTextBody returns the TextBody field value if set, zero value otherwise.
func (o *UpdateTemplateRequest) GetTextBody() string {
	if o == nil || IsNil(o.TextBody) {
		var ret string
		return ret
	}
	return *o.TextBody
}

// GetTextBodyOk returns a tuple with the TextBody field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTemplateRequest) GetTextBodyOk() (*string, bool) {
	if o == nil || IsNil(o.TextBody) {
		return nil, false
	}
	return o.TextBody, true
}

// HasTextBody returns a boolean if a field has been set.
func (o *UpdateTemplateRequest) HasTextBody() bool {
	if o != nil && !IsNil(o.TextBody) {
		return true
	}

	return false
}

// SetTextBody gets a reference to the given string and assigns it to the TextBody field.
func (o *UpdateTemplateRequest) SetTextBody(v string) {
	o.TextBody = &v
}

// GetVariables returns the Variables field value if set, zero value otherwise.
func (o *UpdateTemplateRequest) GetVariables() []TemplateVariable {
	if o == nil || IsNil(o.Variables) {
		var ret []TemplateVariable
		return ret
	}
	return o.Variables
}

// GetVariablesOk returns a tuple with the Variables field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTemplateRequest) GetVariablesOk() ([]TemplateVariable, bool) {
	if o == nil || IsNil(o.Variables) {
		return nil, false
	}
	return o.Variables, true
}

// HasVariables returns a boolean if a field has been set.
func (o *UpdateTemplateRequest) HasVariables() bool {
	if o != nil && !IsNil(o.Variables) {
		return true
	}

	return false
}

// SetVariables gets a reference to the given []TemplateVariable and assigns it to the Variables field.
func (o *UpdateTemplateRequest) SetVariables(v []TemplateVariable) {
	o.Variables = v
}

func (o UpdateTemplateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateTemplateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Subject) {
		toSerialize["subject"] = o.Subject
	}
	if !IsNil(o.HtmlBody) {
		toSerialize["htmlBody"] = o.HtmlBody
	}
	if !IsNil(o.TextBody) {
		toSerialize["textBody"] = o.TextBody
	}
	if !IsNil(o.Variables) {
		toSerialize["variables"] = o.Variables
	}
	return toSerialize, nil
}

type NullableUpdateTemplateRequest struct {
	value *UpdateTemplateRequest
	isSet bool
}

func (v NullableUpdateTemplateRequest) Get() *UpdateTemplateRequest {
	return v.value
}

func (v *NullableUpdateTemplateRequest) Set(val *UpdateTemplateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateTemplateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateTemplateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateTemplateRequest(val *UpdateTemplateRequest) *NullableUpdateTemplateRequest {
	return &NullableUpdateTemplateRequest{value: val, isSet: true}
}

func (v NullableUpdateTemplateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateTemplateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


