/*
Crescendo API

The Crescendo API powers workflow automation and transactional email at scale. Authenticate with a Bearer API key (prefix: `re_...`) obtained from the dashboard.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crescendo

import (
	"encoding/json"
	"time"
)

// checks if the EmailLogResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmailLogResponse{}

// EmailLogResponse struct for EmailLogResponse
type EmailLogResponse struct {
	Id *string `json:"id,omitempty"`
	To *string `json:"to,omitempty"`
	From *string `json:"from,omitempty"`
	Subject *string `json:"subject,omitempty"`
	Status *string `json:"status,omitempty"`
	Provider *string `json:"provider,omitempty"`
	ProviderMessageId *string `json:"providerMessageId,omitempty"`
	Error *string `json:"error,omitempty"`
	TemplateId *string `json:"templateId,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	SentAt *time.Time `json:"sentAt,omitempty"`
	OpenedAt *time.Time `json:"openedAt,omitempty"`
	OpenCount *int32 `json:"openCount,omitempty"`
	ClickCount *int32 `json:"clickCount,omitempty"`
}

// NewEmailLogResponse instantiates a new EmailLogResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmailLogResponse() *EmailLogResponse {
	this := EmailLogResponse{}
	return &this
}

// NewEmailLogResponseWithDefaults instantiates a new EmailLogResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmailLogResponseWithDefaults() *EmailLogResponse {
	this := EmailLogResponse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *EmailLogResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailLogResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *EmailLogResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *EmailLogResponse) SetId(v string) {
	o.Id = &v
}

// GetTo returns the To field value if set, zero value otherwise.
func (o *EmailLogResponse) GetTo() string {
	if o == nil || IsNil(o.To) {
		var ret string
		return ret
	}
	return *o.To
}

// GetToOk returns a tuple with the To field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailLogResponse) GetToOk() (*string, bool) {
	if o == nil || IsNil(o.To) {
		return nil, false
	}
	return o.To, true
}

// HasTo returns a boolean if a field has been set.
func (o *EmailLogResponse) HasTo() bool {
	if o != nil && !IsNil(o.To) {
		return true
	}

	return false
}

// SetTo gets a reference to the given string and assigns it to the To field.
func (o *EmailLogResponse) SetTo(v string) {
	o.To = &v
}

// GetFrom returns the From field value if set, zero value otherwise.
func (o *EmailLogResponse) GetFrom() string {
	if o == nil || IsNil(o.From) {
		var ret string
		return ret
	}
	return *o.From
}

// GetFromOk returns a tuple with the From field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailLogResponse) GetFromOk() (*string, bool) {
	if o == nil || IsNil(o.From) {
		return nil, false
	}
	return o.From, true
}

// HasFrom returns a boolean if a field has been set.
func (o *EmailLogResponse) HasFrom() bool {
	if o != nil && !IsNil(o.From) {
		return true
	}

	return false
}

// SetFrom gets a reference to the given string and assigns it to the From field.
func (o *EmailLogResponse) SetFrom(v string) {
	o.From = &v
}

// GetSubject returns the Subject field value if set, zero value otherwise.
func (o *EmailLogResponse) GetSubject() string {
	if o == nil || IsNil(o.Subject) {
		var ret string
		return ret
	}
	return *o.Subject
}

// GetSubjectOk returns a tuple with the Subject field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailLogResponse) GetSubjectOk() (*string, bool) {
	if o == nil || IsNil(o.Subject) {
		return nil, false
	}
	return o.Subject, true
}

// HasSubject returns a boolean if a field has been set.
func (o *EmailLogResponse) HasSubject() bool {
	if o != nil && !IsNil(o.Subject) {
		return true
	}

	return false
}

// SetSubject gets a reference to the given string and assigns it to the Subject field.
func (o *EmailLogResponse) SetSubject(v string) {
	o.Subject = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *EmailLogResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailLogResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *EmailLogResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *EmailLogResponse) SetStatus(v string) {
	o.Status = &v
}

// GetProvider returns the Provider field value if set, zero value otherwise.
func (o *EmailLogResponse) GetProvider() string {
	if o == nil || IsNil(o.Provider) {
		var ret string
		return ret
	}
	return *o.Provider
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailLogResponse) GetProviderOk() (*string, bool) {
	if o == nil || IsNil(o.Provider) {
		return nil, false
	}
	return o.Provider, true
}

// HasProvider returns a boolean if a field has been set.
func (o *EmailLogResponse) HasProvider() bool {
	if o != nil && !IsNil(o.Provider) {
		return true
	}

	return false
}

// SetProvider gets a reference to the given string and assigns it to the Provider field.
func (o *EmailLogResponse) SetProvider(v string) {
	o.Provider = &v
}

// GetProviderMessageId returns the ProviderMessageId field value if set, zero value otherwise.
func (o *EmailLogResponse) GetProviderMessageId() string {
	if o == nil || IsNil(o.ProviderMessageId) {
		var ret string
		return ret
	}
	return *o.ProviderMessageId
}

// GetProviderMessageIdOk returns a tuple with the ProviderMessageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailLogResponse) GetProviderMessageIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProviderMessageId) {
		return nil, false
	}
	return o.ProviderMessageId, true
}

// HasProviderMessageId returns a boolean if a field has been set.
func (o *EmailLogResponse) HasProviderMessageId() bool {
	if o != nil && !IsNil(o.ProviderMessageId) {
		return true
	}

	return false
}

// SetProviderMessageId gets a reference to the given string and assigns it to the ProviderMessageId field.
func (o *EmailLogResponse) SetProviderMessageId(v string) {
	o.ProviderMessageId = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *EmailLogResponse) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailLogResponse) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *EmailLogResponse) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *EmailLogResponse) SetError(v string) {
	o.Error = &v
}

// GetTemplateId returns the TemplateId field value if set, zero value otherwise.
func (o *EmailLogResponse) GetTemplateId() string {
	if o == nil || IsNil(o.TemplateId) {
		var ret string
		return ret
	}
	return *o.TemplateId
}

// GetTemplateIdOk returns a tuple with the TemplateId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailLogResponse) GetTemplateIdOk() (*string, bool) {
	if o == nil || IsNil(o.TemplateId) {
		return nil, false
	}
	return o.TemplateId, true
}

// HasTemplateId returns a boolean if a field has been set.
func (o *EmailLogResponse) HasTemplateId() bool {
	if o != nil && !IsNil(o.TemplateId) {
		return true
	}

	return false
}

// SetTemplateId gets a reference to the given string and assigns it to the TemplateId field.
func (o *EmailLogResponse) SetTemplateId(v string) {
	o.TemplateId = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *EmailLogResponse) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailLogResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *EmailLogResponse) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *EmailLogResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetSentAt returns the SentAt field value if set, zero value otherwise.
func (o *EmailLogResponse) GetSentAt() time.Time {
	if o == nil || IsNil(o.SentAt) {
		var ret time.Time
		return ret
	}
	return *o.SentAt
}

// GetSentAtOk returns a tuple with the SentAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailLogResponse) GetSentAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.SentAt) {
		return nil, false
	}
	return o.SentAt, true
}

// HasSentAt returns a boolean if a field has been set.
func (o *EmailLogResponse) HasSentAt() bool {
	if o != nil && !IsNil(o.SentAt) {
		return true
	}

	return false
}

// SetSentAt gets a reference to the given time.Time and assigns it to the SentAt field.
func (o *EmailLogResponse) SetSentAt(v time.Time) {
	o.SentAt = &v
}

// GetOpenedAt returns the OpenedAt field value if set, zero value otherwise.
func (o *EmailLogResponse) GetOpenedAt() time.Time {
	if o == nil || IsNil(o.OpenedAt) {
		var ret time.Time
		return ret
	}
	return *o.OpenedAt
}

// GetOpenedAtOk returns a tuple with the OpenedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailLogResponse) GetOpenedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.OpenedAt) {
		return nil, false
	}
	return o.OpenedAt, true
}

// HasOpenedAt returns a boolean if a field has been set.
func (o *EmailLogResponse) HasOpenedAt() bool {
	if o != nil && !IsNil(o.OpenedAt) {
		return true
	}

	return false
}

// SetOpenedAt gets a reference to the given time.Time and assigns it to the OpenedAt field.
func (o *EmailLogResponse) SetOpenedAt(v time.Time) {
	o.OpenedAt = &v
}

// GetOpenCount returns the OpenCount field value if set, zero value otherwise.
func (o *EmailLogResponse) GetOpenCount() int32 {
	if o == nil || IsNil(o.OpenCount) {
		var ret int32
		return ret
	}
	return *o.OpenCount
}

// GetOpenCountOk returns a tuple with the OpenCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailLogResponse) GetOpenCountOk() (*int32, bool) {
	if o == nil || IsNil(o.OpenCount) {
		return nil, false
	}
	return o.OpenCount, true
}

// HasOpenCount returns a boolean if a field has been set.
func (o *EmailLogResponse) HasOpenCount() bool {
	if o != nil && !IsNil(o.OpenCount) {
		return true
	}

	return false
}

// SetOpenCount gets a reference to the given int32 and assigns it to the OpenCount field.
func (o *EmailLogResponse) SetOpenCount(v int32) {
	o.OpenCount = &v
}

// GetClickCount returns the ClickCount field value if set, zero value otherwise.
func (o *EmailLogResponse) GetClickCount() int32 {
	if o == nil || IsNil(o.ClickCount) {
		var ret int32
		return ret
	}
	return *o.ClickCount
}

// GetClickCountOk returns a tuple with the ClickCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailLogResponse) GetClickCountOk() (*int32, bool) {
	if o == nil || IsNil(o.ClickCount) {
		return nil, false
	}
	return o.ClickCount, true
}

// HasClickCount returns a boolean if a field has been set.
func (o *EmailLogResponse) HasClickCount() bool {
	if o != nil && !IsNil(o.ClickCount) {
		return true
	}

	return false
}

// SetClickCount gets a reference to the given int32 and assigns it to the ClickCount field.
func (o *EmailLogResponse) SetClickCount(v int32) {
	o.ClickCount = &v
}

func (o EmailLogResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmailLogResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.To) {
		toSerialize["to"] = o.To
	}
	if !IsNil(o.From) {
		toSerialize["from"] = o.From
	}
	if !IsNil(o.Subject) {
		toSerialize["subject"] = o.Subject
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Provider) {
		toSerialize["provider"] = o.Provider
	}
	if !IsNil(o.ProviderMessageId) {
		toSerialize["providerMessageId"] = o.ProviderMessageId
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.TemplateId) {
		toSerialize["templateId"] = o.TemplateId
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.SentAt) {
		toSerialize["sentAt"] = o.SentAt
	}
	if !IsNil(o.OpenedAt) {
		toSerialize["openedAt"] = o.OpenedAt
	}
	if !IsNil(o.OpenCount) {
		toSerialize["openCount"] = o.OpenCount
	}
	if !IsNil(o.ClickCount) {
		toSerialize["clickCount"] = o.ClickCount
	}
	return toSerialize, nil
}

type NullableEmailLogResponse struct {
	value *EmailLogResponse
	isSet bool
}

func (v NullableEmailLogResponse) Get() *EmailLogResponse {
	return v.value
}

func (v *NullableEmailLogResponse) Set(val *EmailLogResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableEmailLogResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableEmailLogResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmailLogResponse(val *EmailLogResponse) *NullableEmailLogResponse {
	return &NullableEmailLogResponse{value: val, isSet: true}
}

func (v NullableEmailLogResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmailLogResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


