<?php
/**
 * WorkflowsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Crescendo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Crescendo API
 *
 * The Crescendo API powers workflow automation and transactional email at scale. Authenticate with a Bearer API key (prefix: `re_...`) obtained from the dashboard.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Crescendo\Test\Api;

use \Crescendo\Configuration;
use \Crescendo\ApiException;
use \Crescendo\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * WorkflowsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Crescendo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WorkflowsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for activateWorkflow
     *
     * Activate workflow.
     *
     */
    public function testActivateWorkflow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createWorkflow
     *
     * Create workflow.
     *
     */
    public function testCreateWorkflow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deactivateWorkflow
     *
     * Deactivate workflow.
     *
     */
    public function testDeactivateWorkflow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteWorkflow
     *
     * Delete workflow.
     *
     */
    public function testDeleteWorkflow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getWorkflow
     *
     * Get workflow details.
     *
     */
    public function testGetWorkflow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listWorkflows
     *
     * List workflows.
     *
     */
    public function testListWorkflows()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for triggerWorkflow
     *
     * Trigger workflow.
     *
     */
    public function testTriggerWorkflow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateWorkflow
     *
     * Update workflow.
     *
     */
    public function testUpdateWorkflow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
