/*
 * Crescendo API
 * The Crescendo API powers workflow automation and transactional email at scale. Authenticate with a Bearer API key (prefix: `re_...`) obtained from the dashboard.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.crescendo.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.crescendo.model.TemplateVariable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.crescendo.ApiClient;
/**
 * CreateTemplateRequest
 */
@JsonPropertyOrder({
  CreateTemplateRequest.JSON_PROPERTY_NAME,
  CreateTemplateRequest.JSON_PROPERTY_SUBJECT,
  CreateTemplateRequest.JSON_PROPERTY_HTML_BODY,
  CreateTemplateRequest.JSON_PROPERTY_TEXT_BODY,
  CreateTemplateRequest.JSON_PROPERTY_VARIABLES
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-07T13:05:45.810490+05:30[Asia/Kolkata]", comments = "Generator version: 7.23.0")
public class CreateTemplateRequest {
  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_SUBJECT = "subject";
  @jakarta.annotation.Nonnull
  private String subject;

  public static final String JSON_PROPERTY_HTML_BODY = "htmlBody";
  @jakarta.annotation.Nonnull
  private String htmlBody;

  public static final String JSON_PROPERTY_TEXT_BODY = "textBody";
  @jakarta.annotation.Nullable
  private String textBody;

  public static final String JSON_PROPERTY_VARIABLES = "variables";
  @jakarta.annotation.Nullable
  private List<TemplateVariable> variables = new ArrayList<>();

  public CreateTemplateRequest() { 
  }

  public CreateTemplateRequest name(@jakarta.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@jakarta.annotation.Nonnull String name) {
    this.name = name;
  }


  public CreateTemplateRequest subject(@jakarta.annotation.Nonnull String subject) {
    this.subject = subject;
    return this;
  }

  /**
   * Get subject
   * @return subject
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SUBJECT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getSubject() {
    return subject;
  }


  @JsonProperty(value = JSON_PROPERTY_SUBJECT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSubject(@jakarta.annotation.Nonnull String subject) {
    this.subject = subject;
  }


  public CreateTemplateRequest htmlBody(@jakarta.annotation.Nonnull String htmlBody) {
    this.htmlBody = htmlBody;
    return this;
  }

  /**
   * Get htmlBody
   * @return htmlBody
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_HTML_BODY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getHtmlBody() {
    return htmlBody;
  }


  @JsonProperty(value = JSON_PROPERTY_HTML_BODY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setHtmlBody(@jakarta.annotation.Nonnull String htmlBody) {
    this.htmlBody = htmlBody;
  }


  public CreateTemplateRequest textBody(@jakarta.annotation.Nullable String textBody) {
    this.textBody = textBody;
    return this;
  }

  /**
   * Get textBody
   * @return textBody
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TEXT_BODY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTextBody() {
    return textBody;
  }


  @JsonProperty(value = JSON_PROPERTY_TEXT_BODY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTextBody(@jakarta.annotation.Nullable String textBody) {
    this.textBody = textBody;
  }


  public CreateTemplateRequest variables(@jakarta.annotation.Nullable List<TemplateVariable> variables) {
    this.variables = variables;
    return this;
  }

  public CreateTemplateRequest addVariablesItem(TemplateVariable variablesItem) {
    if (this.variables == null) {
      this.variables = new ArrayList<>();
    }
    this.variables.add(variablesItem);
    return this;
  }

  /**
   * Get variables
   * @return variables
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VARIABLES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<TemplateVariable> getVariables() {
    return variables;
  }


  @JsonProperty(value = JSON_PROPERTY_VARIABLES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVariables(@jakarta.annotation.Nullable List<TemplateVariable> variables) {
    this.variables = variables;
  }


  /**
   * Return true if this CreateTemplateRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateTemplateRequest createTemplateRequest = (CreateTemplateRequest) o;
    return Objects.equals(this.name, createTemplateRequest.name) &&
        Objects.equals(this.subject, createTemplateRequest.subject) &&
        Objects.equals(this.htmlBody, createTemplateRequest.htmlBody) &&
        Objects.equals(this.textBody, createTemplateRequest.textBody) &&
        Objects.equals(this.variables, createTemplateRequest.variables);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, subject, htmlBody, textBody, variables);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateTemplateRequest {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    htmlBody: ").append(toIndentedString(htmlBody)).append("\n");
    sb.append("    textBody: ").append(toIndentedString(textBody)).append("\n");
    sb.append("    variables: ").append(toIndentedString(variables)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `subject` to the URL query string
    if (getSubject() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssubject%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSubject()))));
    }

    // add `htmlBody` to the URL query string
    if (getHtmlBody() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%shtmlBody%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHtmlBody()))));
    }

    // add `textBody` to the URL query string
    if (getTextBody() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stextBody%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTextBody()))));
    }

    // add `variables` to the URL query string
    if (getVariables() != null) {
      for (int i = 0; i < getVariables().size(); i++) {
        if (getVariables().get(i) != null) {
          joiner.add(getVariables().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%svariables%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

