/*
 * Crescendo API
 * The Crescendo API powers workflow automation and transactional email at scale. Authenticate with a Bearer API key (prefix: `re_...`) obtained from the dashboard.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.crescendo.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.crescendo.model.DailyCount;
import io.crescendo.model.MetricsSummary;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.crescendo.ApiClient;
/**
 * MetricsResponse
 */
@JsonPropertyOrder({
  MetricsResponse.JSON_PROPERTY_SUMMARY,
  MetricsResponse.JSON_PROPERTY_DAILY
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-07T13:05:45.810490+05:30[Asia/Kolkata]", comments = "Generator version: 7.23.0")
public class MetricsResponse {
  public static final String JSON_PROPERTY_SUMMARY = "summary";
  @jakarta.annotation.Nullable
  private MetricsSummary summary;

  public static final String JSON_PROPERTY_DAILY = "daily";
  @jakarta.annotation.Nullable
  private List<DailyCount> daily = new ArrayList<>();

  public MetricsResponse() { 
  }

  public MetricsResponse summary(@jakarta.annotation.Nullable MetricsSummary summary) {
    this.summary = summary;
    return this;
  }

  /**
   * Get summary
   * @return summary
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SUMMARY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public MetricsSummary getSummary() {
    return summary;
  }


  @JsonProperty(value = JSON_PROPERTY_SUMMARY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSummary(@jakarta.annotation.Nullable MetricsSummary summary) {
    this.summary = summary;
  }


  public MetricsResponse daily(@jakarta.annotation.Nullable List<DailyCount> daily) {
    this.daily = daily;
    return this;
  }

  public MetricsResponse addDailyItem(DailyCount dailyItem) {
    if (this.daily == null) {
      this.daily = new ArrayList<>();
    }
    this.daily.add(dailyItem);
    return this;
  }

  /**
   * Get daily
   * @return daily
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DAILY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<DailyCount> getDaily() {
    return daily;
  }


  @JsonProperty(value = JSON_PROPERTY_DAILY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDaily(@jakarta.annotation.Nullable List<DailyCount> daily) {
    this.daily = daily;
  }


  /**
   * Return true if this MetricsResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MetricsResponse metricsResponse = (MetricsResponse) o;
    return Objects.equals(this.summary, metricsResponse.summary) &&
        Objects.equals(this.daily, metricsResponse.daily);
  }

  @Override
  public int hashCode() {
    return Objects.hash(summary, daily);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MetricsResponse {\n");
    sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
    sb.append("    daily: ").append(toIndentedString(daily)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `summary` to the URL query string
    if (getSummary() != null) {
      joiner.add(getSummary().toUrlQueryString(prefix + "summary" + suffix));
    }

    // add `daily` to the URL query string
    if (getDaily() != null) {
      for (int i = 0; i < getDaily().size(); i++) {
        if (getDaily().get(i) != null) {
          joiner.add(getDaily().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sdaily%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

