/*
 * Crescendo API
 * The Crescendo API powers workflow automation and transactional email at scale. Authenticate with a Bearer API key (prefix: `re_...`) obtained from the dashboard.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.crescendo.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.crescendo.model.SortObject;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.crescendo.ApiClient;
/**
 * PageableObject
 */
@JsonPropertyOrder({
  PageableObject.JSON_PROPERTY_PAGED,
  PageableObject.JSON_PROPERTY_PAGE_NUMBER,
  PageableObject.JSON_PROPERTY_PAGE_SIZE,
  PageableObject.JSON_PROPERTY_SORT,
  PageableObject.JSON_PROPERTY_UNPAGED,
  PageableObject.JSON_PROPERTY_OFFSET
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-07T13:05:45.810490+05:30[Asia/Kolkata]", comments = "Generator version: 7.23.0")
public class PageableObject {
  public static final String JSON_PROPERTY_PAGED = "paged";
  @jakarta.annotation.Nullable
  private Boolean paged;

  public static final String JSON_PROPERTY_PAGE_NUMBER = "pageNumber";
  @jakarta.annotation.Nullable
  private Integer pageNumber;

  public static final String JSON_PROPERTY_PAGE_SIZE = "pageSize";
  @jakarta.annotation.Nullable
  private Integer pageSize;

  public static final String JSON_PROPERTY_SORT = "sort";
  @jakarta.annotation.Nullable
  private SortObject sort;

  public static final String JSON_PROPERTY_UNPAGED = "unpaged";
  @jakarta.annotation.Nullable
  private Boolean unpaged;

  public static final String JSON_PROPERTY_OFFSET = "offset";
  @jakarta.annotation.Nullable
  private Long offset;

  public PageableObject() { 
  }

  public PageableObject paged(@jakarta.annotation.Nullable Boolean paged) {
    this.paged = paged;
    return this;
  }

  /**
   * Get paged
   * @return paged
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PAGED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getPaged() {
    return paged;
  }


  @JsonProperty(value = JSON_PROPERTY_PAGED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPaged(@jakarta.annotation.Nullable Boolean paged) {
    this.paged = paged;
  }


  public PageableObject pageNumber(@jakarta.annotation.Nullable Integer pageNumber) {
    this.pageNumber = pageNumber;
    return this;
  }

  /**
   * Get pageNumber
   * @return pageNumber
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PAGE_NUMBER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getPageNumber() {
    return pageNumber;
  }


  @JsonProperty(value = JSON_PROPERTY_PAGE_NUMBER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPageNumber(@jakarta.annotation.Nullable Integer pageNumber) {
    this.pageNumber = pageNumber;
  }


  public PageableObject pageSize(@jakarta.annotation.Nullable Integer pageSize) {
    this.pageSize = pageSize;
    return this;
  }

  /**
   * Get pageSize
   * @return pageSize
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PAGE_SIZE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getPageSize() {
    return pageSize;
  }


  @JsonProperty(value = JSON_PROPERTY_PAGE_SIZE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPageSize(@jakarta.annotation.Nullable Integer pageSize) {
    this.pageSize = pageSize;
  }


  public PageableObject sort(@jakarta.annotation.Nullable SortObject sort) {
    this.sort = sort;
    return this;
  }

  /**
   * Get sort
   * @return sort
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SORT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public SortObject getSort() {
    return sort;
  }


  @JsonProperty(value = JSON_PROPERTY_SORT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSort(@jakarta.annotation.Nullable SortObject sort) {
    this.sort = sort;
  }


  public PageableObject unpaged(@jakarta.annotation.Nullable Boolean unpaged) {
    this.unpaged = unpaged;
    return this;
  }

  /**
   * Get unpaged
   * @return unpaged
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_UNPAGED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getUnpaged() {
    return unpaged;
  }


  @JsonProperty(value = JSON_PROPERTY_UNPAGED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUnpaged(@jakarta.annotation.Nullable Boolean unpaged) {
    this.unpaged = unpaged;
  }


  public PageableObject offset(@jakarta.annotation.Nullable Long offset) {
    this.offset = offset;
    return this;
  }

  /**
   * Get offset
   * @return offset
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OFFSET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getOffset() {
    return offset;
  }


  @JsonProperty(value = JSON_PROPERTY_OFFSET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOffset(@jakarta.annotation.Nullable Long offset) {
    this.offset = offset;
  }


  /**
   * Return true if this PageableObject object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PageableObject pageableObject = (PageableObject) o;
    return Objects.equals(this.paged, pageableObject.paged) &&
        Objects.equals(this.pageNumber, pageableObject.pageNumber) &&
        Objects.equals(this.pageSize, pageableObject.pageSize) &&
        Objects.equals(this.sort, pageableObject.sort) &&
        Objects.equals(this.unpaged, pageableObject.unpaged) &&
        Objects.equals(this.offset, pageableObject.offset);
  }

  @Override
  public int hashCode() {
    return Objects.hash(paged, pageNumber, pageSize, sort, unpaged, offset);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PageableObject {\n");
    sb.append("    paged: ").append(toIndentedString(paged)).append("\n");
    sb.append("    pageNumber: ").append(toIndentedString(pageNumber)).append("\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("    sort: ").append(toIndentedString(sort)).append("\n");
    sb.append("    unpaged: ").append(toIndentedString(unpaged)).append("\n");
    sb.append("    offset: ").append(toIndentedString(offset)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `paged` to the URL query string
    if (getPaged() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spaged%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPaged()))));
    }

    // add `pageNumber` to the URL query string
    if (getPageNumber() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spageNumber%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPageNumber()))));
    }

    // add `pageSize` to the URL query string
    if (getPageSize() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spageSize%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPageSize()))));
    }

    // add `sort` to the URL query string
    if (getSort() != null) {
      joiner.add(getSort().toUrlQueryString(prefix + "sort" + suffix));
    }

    // add `unpaged` to the URL query string
    if (getUnpaged() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sunpaged%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUnpaged()))));
    }

    // add `offset` to the URL query string
    if (getOffset() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%soffset%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOffset()))));
    }

    return joiner.toString();
  }
}

